### ISSUE TITLE
How can I set the room for a periodic task?

### ISSUE THREAD

**Issue by camilonova** [skoczen/will#100]
I look here http://skoczen.github.io/will/plugins/notice/ and in the code but didn't find how to tell which room to use, how it works?

**Comment by skoczen** [comment]
Hey @camilonova - the room specification will come when you do the `self.say()`s  - take a look at [how will can respond!](http://skoczen.github.io/will/plugins/reply/).

Or am I misunderstanding, and you only want your will to hear certain events from certain rooms?

**Comment by camilonova** [comment]
This is it:

    Note that we pass messsage along. This allows will to route his reply to the correct room. Without it, he'll just speak to the DEFAULT_ROOM.

Thank you.

**Comment by skoczen** [comment]
Happy you got it all figured out!
