### ISSUE TITLE
WORLD_WEATHER_ONLINE_V2_KEY not being read

### ISSUE THREAD

**Issue by fxer** [skoczen/will#106]
I set the WORLD_WEATHER_ONLINE_V2_KEY in the bin/postactivate of my bot, and reactivated it (I can echo $WORLD_WEATHER_ONLINE_V2_KEY and see the key) but I can't get Will to recognize it, just says "you need an WORLD_WEATHER_ONLINE_V2_KEY to do that"

Does the key not go into the environment?

**Comment by fxer** [comment]
Indeed it appears it is not an environment variable, it goes in config.py. Same with HANGOUT_URL, probably would be handy to mention in the docs :)

**Comment by skoczen** [comment]
Hey, so either the environment or config.py will work.

Environment variables are namespaced, i.e.
```
export WILL_HANGOUT_URL="132235"
```

Config.py variables are not:
```
HANGOUT_URL="12314"
```

Documentation is here:

http://skoczen.github.io/will/config/  , specifically "All environment variables prefixed with WILL_ are imported into will's settings modules."

There's also a section detailing how environment variable and config.py variables are combined:
http://skoczen.github.io/will/config/#how-environment-variables-and-configpy-are-combined

If you have suggestions on how to make that clearer, I'm all ears!

Thanks,
-Steven
