### ISSUE TITLE
[improvement] ACL Design Pattern - ability to define ACLs in a flexible way

### ISSUE THREAD

**Issue by woohgit** [skoczen/will#109]
Hey,

I open this issue, to have a little brainstorm about what could be done related to facelift the ACL levels in will. I think I'm not the only one who would need this. I'd like to discuss a few ACL designs. I'm pretty open to implement it as well.

I personally love this approach. Instead using the following existing ACL:

```python
@respond_to("something", admin_only=True)
```

I'd rather go with a parameter called `acl` which would accept a [set](https://docs.python.org/3/library/stdtypes.html#set) as a parameter. like this:

```python
@respond_to("something", acl={"infra_admin", "infra_ops", "infra_developer"})
```

To keep it compatible, we can keep the `admin_only=True` as well and add the `acl` as an optional parameter.

The definition of the ACLs for my example would look like this:

```python
ACL_INFRA_OPS = []
ACL_INFRA_ADMIN = []
ACL_INFRA_DEVELOPER = []
```
If an ACL definition does not exists, simply "skip" that ACL check and notify the requester, that the given ACL group does not exists.

What do you think?

**Comment by skoczen** [comment]
As I noted in #109, I'm a +1 to this, but want to give it some good thought re: verbage, language, etc - my main goal is to give ACL power to users without it feeling super administrative-y.  

Will definitely get this merged in though!
