### ISSUE TITLE
How to add custom help text to module?

### ISSUE THREAD

**Issue by fxer** [skoczen/will#111]
Following the directions on the plugin page about adding MODULE_DESCRIPTION to \__init__.py, and the triple quoted """ some help text """ inside my plugin.py file, I still can't get `@will help` to add my custom help text to his output.

The folder layout is basically
will/
&nbsp;&nbsp;&nbsp;&nbsp;plugins/
&nbsp;&nbsp;&nbsp;&nbsp;\__init__.py
&nbsp;&nbsp;&nbsp;&nbsp;\__init__.pyc
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;custom/
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;\__init__.py
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;plugin_name.py

Is it a problem with the nesting? The plugin loads and works fine, just I don't see my MODULE_NAME or custom help text in will's output

**Comment by skoczen** [comment]
Just for clarity, I'm assuming you have `__init__.py`'s in all the containing folders as well?

Will dig into this a bit further when I have cycles.  If you can paste the relevant sections of your config as well, that'd be great.  Thanks!

**Comment by fxer** [comment]
Right, I simplified the folder structure a bit and updated it in my original post. Still same problem though, neither MODULE_DESCRIPTION from either \__init__.py is loading

**Comment by skoczen** [comment]
Can you paste your config + the plugin source?

Thanks much for putting the time in - it helps greatly with debugging what's different in your setup!

**Comment by skoczen** [comment]
Same as other issue -  tidying up it's been a while since I've heard on this one.

If you're still having trouble, please re-open with the details!

Thanks,
Steven
