### ISSUE TITLE
Where does will log to?

### ISSUE THREAD

**Issue by fxer** [skoczen/will#112]
Enabling the setting `LOGLEVEL=DEBUG`, where should will be logging to? I don't see anything in the app dir (which his user owns) or in /var/log ?

**Comment by woohgit** [comment]
Will logs to stdout/stderr as far as I know, so it's not writing to any specific logs. You need to have a wrapper around will for example upstart, init.d, systemd and tell the supervisor process to log to a specific file the stdout/stderr messages from your will process.

**Comment by skoczen** [comment]
Hey @fxer ,

Yep, will just outputs via then normal python [logging](https://docs.python.org/2/library/logging.html) module.  You can set up output however you'd like.

By default, as @woohgit mentions, it's stdout/stderr.  

Closing this up - please reopen if you have further questions!

-Steven
