### ISSUE TITLE
ERROR: We ran into trouble: 'Invalid OAuth session'

### ISSUE THREAD

**Issue by dlaikhter** [skoczen/will#113]
Hi I'm dumb and keep getting 'ERROR: We ran into trouble: 'Invalid OAuth session.'  I'm pretty certain that all my credentials are correct, so I was wondering if anybody has any troubleshooting experience with this.

Thanks!

**Comment by skoczen** [comment]
@dlaikhter how old is your will install? About a year?

If yes, please just regenerate and update your V2 token.  It's a known and undocumented issue/spec at hipchat that V2 tokens expire after 1 year. 

Work on a long-term, permanent fix (that will also reduce the number of required creds) is happening [here](https://github.com/skoczen/will/pull/102), but it's not ready yet.

Thanks for your patience!

**Comment by skoczen** [comment]
Also, if it's a brand-new install, we can troubleshoot your config and get it running!

**Comment by dlaikhter** [comment]
brand-new install

**Comment by skoczen** [comment]
Ah, cool. 

In that case, I'd bet strongly that one of your credentials is wrong.

Best guess is the V2 token, or the email - about to run now, but will have more debug info in a couple hours, if it helps.   For now, check that you're getting the token correctly, that it's an admin token, and that the email is the hipchat JID email, not login email.

Thanks for your patience!

**Comment by dlaikhter** [comment]
Don't think the account is an admin, that might be it.

**Comment by skoczen** [comment]
So the V1 token is admin.  The V2 is for will's user (separate user at hipchat), and his personal v2 token.

**Comment by skoczen** [comment]
Hey @dlaikhter ,

I'm just tidying up issues - since it's been a while since I've heard on this one, I'm closing it up.  If you're still having trouble, please re-open with the details!

Thanks,
Steven

**Comment by schleppy** [comment]
@skoczen 

I am running into the same issue.  I got the Jabber ID, the correct password, and a V2 token generated by going to API access.  I read all of the comments above but am a little confused by these comments:

"For now, check that you're getting the token correctly, that it's an admin token..."
"So the V1 token is admin. The V2 is for will's user (separate user at hipchat), and his personal v2 token."
and the env var name of `WILL_V2_TOKEN`.

It seems I need a V2 token, but you say that it needs to be an admin token, and that V1 is admin.  Can you shed some light on this for me?

**Comment by schleppy** [comment]
@skoczen 

Disregard.  For future readers I was connecting to a hosted hip-chat and did not set the HIPCHAT_SERVER value in config.py.

**Comment by chillipeper** [comment]
Hey, 

I am also experiencing the same issue.

Verifying credentials...
ERROR: We ran into trouble: 'Invalid OAuth session'

I have verified user name and password are the right ones. Even tested them on a separate XMPP Client.

Anyway I can debug this?
