### ISSUE TITLE
Can Will be used to play some music?

### ISSUE THREAD

**Issue by brandonsturgeon** [skoczen/will#123]
I looked into adding this feature myself, but I couldn't find any good Pandora/Radio modules that could be used. Many of them used programs that required keypresses to end (eg: press Q to quit the radio) which isn't optimal for something like Will. 

Though I am still learning, so your input would be greatly appreciated. I'd love to be able to do something like "@will play some music" and it would play a random station, or maybe "@will play some jazz" and it'd play a jazz station. And if Pandora was accepted, being able to say "@will I hate this song" would thumbs down the song, things like that. 

How do-able would a feature like this be?

**Comment by skoczen** [comment]
Hey @brandonsturgeon , I'd personally *love* something like this - our team is distributed, and we've been craving a remote music system.

However, for will to be able to control it, you'd be looking for a music service with an API that allowed you to control playback, thumbs up/down/etc.

If you can find one of those, such a feature shouldn't be too bad!  [Rdio](http://www.rdio.com/developers/) might be a good place to start - they're pretty cool and API-driven.

**Comment by camilonova** [comment]
@brandonsturgeon I did it with mopidy and the HTTP RPC API.

See https://github.com/AxiaCore/will/blob/master/plugins/axiacore.py#L65

**Comment by brandonsturgeon** [comment]
@camilonova Excellent! Looks perfect. Was there any special setup you had to do on the Mopidy end?

**Comment by camilonova** [comment]
@brandonsturgeon nope

**Comment by brandonsturgeon** [comment]
@camilonova Ha ha! That's perfect! I can't quite get it to do anything with Google Music or Spotify just yet, but I'm still playing around. There was quite a bit of setup involved, and I wasn't able to successfully get Mopidy installed on my CentOS 7 machine, but I just ended up putting it on a Mac Mini I had lying around. I learned a lot though, and it was a fun experience!

Thanks so much!

**Comment by skoczen** [comment]
Just started digging into this, and love it so much.   I won't be able to grok it well enough to get it into this afternoon's mad-dash of a release, but I do want to get something like this built in!

@camilonova any chance you can put together a PR based on what you've got?

**Comment by brandonsturgeon** [comment]
@skoczen I've been working extensively on this in the last day or so, and I've put together something really cool. `@will play some tunes` or `@will play us some smooth jazz please` and `@will turn it up!` `@will set the volume to 5` all work. However, it's pretty complex and definitely not platform independent.

 I'm certainly no expert, but I don't see any easy way to make Will play music on any platform while still sticking to Will's current theme of minimal setup.

**Comment by camilonova** [comment]
@skoczen I can do that.

**Comment by skoczen** [comment]
@brandonsturgeon I'm thinking along the lines of a simple API for will, that then can be configured / plugged into a more extensive library.  It's possible this won't make sense as a built-in will module, but since this happens to scratch an itch I have *right now* at my startup, I'm also willing to invest into seeing what can be done on the will side.  Maybe that'll help, maybe not. :)

@camilonova awesome, thanks!

**Comment by camilonova** [comment]
I just created a grooveshark backend for mopidy

https://github.com/camilonova/mopidy-grooveshark

**Comment by brandonsturgeon** [comment]
@camilonova On the topic, how would you get Hubot to play something from Google Music? Haven't been having any luck on that end. And what would you prefix links from Grooveshark with? For example, you prefixed all Youtube links with `yt: ` and I found you had to do `sc: ` for soundcloud. But I can't figure out how to make Will deal with Google Play links. The Google Music should be all set up on the Mopidy end.

**Comment by camilonova** [comment]
@brandonsturgeon about google play it will depend on the backend https://github.com/hechtus/mopidy-gmusic 

Seems their prefix is ```gmusic:``` we don't use google play so I can't provide more help on that.

**Comment by brandonsturgeon** [comment]
Using Mopidy I was able to set up a pretty comprehensive music system with Will. I was even able to get him to Stream WHILE playing music so that the people working from home could still listen to and control the music.
