### ISSUE TITLE
Quotations still working?

### ISSUE THREAD

**Issue by jessamynsmith** [skoczen/will#124]
Hi Steven,

I've updated the code behind the underquoted API -- could you please confirm that will is still able to retrieve quotations?

Thanks!

**Comment by skoczen** [comment]
Yep, still working here!  Anything in particular I should be on the lookout for?

**Comment by jessamynsmith** [comment]
Just that you can still retrieve quotations :)

I did a lot of small upgrades to the app, and I can't test the will plugin myself, so I appreciate you checking.

I'm about to refactor the code behind the API, so please leave this open for now. I'll let you know when I'm done and you can check again.

Cheers!

**Comment by skoczen** [comment]
This is in, works great, and is released (with a bunch of other stuff) in v[0.8](http://skoczen.github.io/will/improve/#releases)!

**Comment by jessamynsmith** [comment]
Hooray!
