### ISSUE TITLE
Will randomly not joining rooms?

### ISSUE THREAD

**Issue by brandonsturgeon** [skoczen/will#126]
My Will bot was working splendidly, then today I restarted him and he wouldn't join any rooms. You can still talk to him in private chat, but he doesn't show as being online in any of the channels he's supposed to join. In the room "users" list, his little hipchat circle is greyed out. It's still green next to his name in the private chat section, though.

On startup it says the he joined the rooms he was supposed to, but he's not actually there. I verified on the hipchat website that he had access to those rooms. Really not sure what's going on.

Some help in troubleshooting this would be greatly appreciated.

EDIT: Not sure if relevant, but sometimes when he starts it'll just show "Will has left the room" in the room. Other times not. Asking him `what are the rooms?` clearly shows all of the rooms he can access.

EDIT2: Turned on Debug Loglevel, and I saw where it was joining rooms it would look something like this:
`INFO Starting new HTTPS connection(): api.hipchat.com`
`DEBUG  "GET /v2/room/blahblah/?auth_token=blahblah;expand=xmpp_jid HTTP/1.1"`and each line for each room a had a 404 afterwards, some followed by a 97 and some followed by None. 
eg: `"GET blahblahblah HTTP/1.1" 404 97`

EDIT3: Found something interesting:
`api.hipchat.com/v2/room/ID/?auth_token=AUTHTOKEN` (which is the URL being posted in DEBUG output) throws a 404 and says it can't find the room
however, `api.hipchat.com/v2/room/ID?auth_token=AUTHTOKEN` returns information about the room.

Assuming this is a problem and I'm not just going crazy, it looks like the extra backslash on this line is causing the issue:
https://github.com/skoczen/will/blob/master/will/mixins/room.py#L49

EDIT4: I changed my local Will installation in `/usr/lib/python2.7/site-packages/will/` and removed the extra backslash from that line, and everything started working again. Will joins all of my rooms now, and the Debug shows that the GETs are receiving a 200 success code. This doesn't make any sense because that line hasn't been touched in 2 months. Hipchat must have changed something, then? Anyway, I've got mine working now.

What a night.

**Comment by brandonsturgeon** [comment]
I opened a pull request just in case this ends up being something that needs to be changed.

**Comment by woohgit** [comment]
Right, this has been changed a few hrs ago, I've pinged HipChat about it. I wonder if they fix it or we well need to change our  code.

**Comment by skoczen** [comment]
Thanks for the debugging, and PR @brandonsturgeon and @woohgit  - will get a hotfix out for this shortly!

**Comment by skoczen** [comment]
This is fixed, and released (with a bunch of other stuff) in v[0.8](http://skoczen.github.io/will/improve/#releases)!
