### ISSUE TITLE
Heroku Timeout

### ISSUE THREAD

**Issue by camilonova** [skoczen/will#131]
This just start happening today:

```
2015-05-01T18:22:37.703051+00:00 app[web.1]:     ✓ USERNAME
2015-05-01T18:22:37.703129+00:00 app[web.1]:     ✓ USE_PROXY
2015-05-01T18:22:37.703189+00:00 app[web.1]:     ✓ V2_TOKEN
2015-05-01T18:22:37.703216+00:00 app[web.1]:
2015-05-01T18:22:37.703220+00:00 app[web.1]: Verifying rooms...
2015-05-01T18:22:37.700233+00:00 app[web.1]:   ✓ Will authenticated
2015-05-01T18:23:30.006635+00:00 heroku[web.1]: Error R10 (Boot timeout) -> Web process failed to bind to $PORT within 60 seconds of launch
2015-05-01T18:23:30.006935+00:00 heroku[web.1]: Stopping process with SIGKILL
2015-05-01T18:23:30.805806+00:00 heroku[web.1]: State changed from starting to crashed
2015-05-01T18:23:30.794998+00:00 heroku[web.1]: Process exited with status 137
```

Do you know how we can debug this?

I have tried to restart, deactivating plugins and nothing works.

**Comment by skoczen** [comment]
Make sure you're not setting the `PORT` environment variable, or `HTTPSERVER_PORT` in `config.py`.  If those aren't set, will will use heroku's default `PORT` variable, and bind to the correct port.

**Comment by camilonova** [comment]
This is all I got:
![1__camilonova_axc____dropbox_workspace_will__zsh_](https://cloud.githubusercontent.com/assets/202559/7435271/c749f958-f007-11e4-846e-95970f4d9c6e.png)

**Comment by camilonova** [comment]
This is the config.py https://github.com/AxiaCore/will/blob/master/config.py

**Comment by skoczen** [comment]
Darn.  That all looks right.

**Comment by skoczen** [comment]
Let me restart my wills, and make sure nothing's happening on the heroku side.

**Comment by camilonova** [comment]
Thanks

**Comment by skoczen** [comment]
All clean here.

So, that's hanging pretty early, and from what I can see on your traceback, it's right at the part where we're getting the hipchat user, and setting that data in the env, so all the threads can get to it.

```python
        q = Queue()
        p = Process(target=self.get_hipchat_user, args=(user_id,), kwargs={"q": q, })
        p.start()
        user_data = q.get()
        p.join()

        if "error" in user_data:
            error("We ran into trouble: '%(message)s'" % user_data["error"])
            sys.exit(1)
        with indent(2):
            show_valid("%s authenticated" % user_data["name"])
            os.environ["WILL_NAME"] = user_data["name"]
            show_valid("@%s verified as handle" % user_data["mention_name"])
            os.environ["WILL_HANDLE"] = user_data["mention_name"]
```

This is a weird one.  So possibilities:
- Weird DNS threadsafe stuff
- Trouble / config change on your hipchat's will account.
- Hipchat bugs.
- Heroku env bugs (less likely)
- Something else.

So, to start debugging, can you post the basics:

- Python version
- If it works locally, etc
- Any changes in your hipchat/heroku config recently?
- I assume this was working before at heroku?
- Other stuff that seems relevant! :)

We'll get there - know it's super annoying to have stuff like this pop up.  I'm not seeing it here, so am hopeful it's something config-y, or an errant semicolon somewhere.

**Comment by camilonova** [comment]
Ok, it was working fine yesterday, I did some changes but I reverted them and push again changes, it doesn't work.

I'm using python 2.7 and it was working fine, I haven't changed anything important, you can see the changes on our will.

There is any way to start will in 'safe mode' just with the basic stuff ?

**Comment by camilonova** [comment]
Seems it hangs when ```Verifying rooms...```

**Comment by camilonova** [comment]
It hangs when ```Verifying rooms...```

I have regenerated the ```V2_TOKEN``` and is still failing. Can you try to get the rooms locally?

**Comment by skoczen** [comment]
Ok, that can make more sense.  How many rooms do you have?  If it's more than say, 30, you'll [need a V1 token as well](http://skoczen.github.io/will/deploy/). 

This is because of a long-standing bug in the hipchat v2 api that's been finally fixed, but for which will isn't yet updated to.

**Comment by camilonova** [comment]
I have changed this ```ROOMS = ['AxiaCore',]``` and seems up, but is not responding on one on one.

**Comment by skoczen** [comment]
Yeah, so it's not actually the number you've asked will to join, it's the total number for your org.

**Comment by camilonova** [comment]
I have 26 rooms half of them inactive

**Comment by camilonova** [comment]
I have set the ```V1_TOKEN``` and now is working, seems the limit is not 30 but less than that.

Can we change something to count the rooms and warn when you actually need the ```V1_TOKEN``` ?

Right now is:
```
Warning: no V1_TOKEN found in the environment or config.This is generally ok, but if you have more than 30 rooms, you may recieve rate-limit errors without one.
```

**Comment by camilonova** [comment]
I didn't receive any rate-limit error

**Comment by skoczen** [comment]
Awesome, glad it's working.

The long-term-fix for this is to eliminate the V1 token entirely, which will ultimately be what #102 accomplishes (since V2 tokens have their own issues, with hidden magical hipchat expire times).

Any and all help on 102 is very welcome - it's super gnarly, and I'm struggling with it.

An alternate, shorter-term fix is to change the rooms-gathering code from using the V1 token to the V2 token, since the hipchat API bug has been fixed.

If you've got cycles for either of those, the help is very welcome!

**Comment by camilonova** [comment]
I think I can have time at the end of the next week, ping me later and give me some basic instructions and I'll try it to do it on my own.

Thanks.

**Comment by skoczen** [comment]
Fantastic - which are you looking to take on?   The XMPP stuff, or the V2 rooms api?

Thanks!

**Comment by camilonova** [comment]
V2 rooms api

**Comment by skoczen** [comment]
Cool, will spec it out - should be fairly easy.
