### ISSUE TITLE
Restart Will / Reload plug-ins?

### ISSUE THREAD

**Issue by brandonsturgeon** [skoczen/will#133]
I've made my plug-ins folder a git repo, and I'd love to be able to tell will to pull the latest updates and then reload the files. I've got the first part down, but I don't know how to go about reloading will or the scripts. 

Would I have to make another script that restarts will, and then make will call out to it on command?  Or would that not work because Will would be running the script that restarted itself? Sorta confusing how they works. 

Anyway, is this possible?

**Comment by skoczen** [comment]
Hey,

So the way you have it set up is a bit antipattern, and is going to be really difficult to get working.

The recommended way to set it up is to have your will and the plugins in one repo, and then to set up continuous deployment.

The end effect is the same - you push code, tests are run, and then if they pass, your will is reloaded with the new functionality.

Is there are reason that pattern doesn't work for your setup?

Thanks!
-Steven

**Comment by neronmoon** [comment]
For some reasons i have to implement this antipattern. @brandonsturgeon can take a look at this code.
Plugin:
```Python
@respond_to('restart', admin_only=True)
def restart(self, message):
    """restart: restarts Will"""
    self.say("FYI. I'm going to restart", message=message)
    os.execl('bin/restart.sh', '')
@respond_to('upgrade', admin_only=True)
def upgrade(self, message):
    """upgrade: upgrade and restart Will"""
    commands.getoutput("git reset --hard; git pull")
    self.restart(message)
```

restart.sh
```bash
#!/bin/bash

pkill -f "run_will.py"
sleep 10
python /var/projects/boris-the-bot/run_will.py &> /tmp/boris.log 2> /tmp/boris.err &
```

**Comment by skoczen** [comment]
Hey @neronmoon , 

The pattern you're following isn't one I'm going to be able to support here, unfortunately.   If there are things we can dig into why the recommended pattern won't work for your setup, I'm happy to, but this particular setup is outside the scope of will (and my expertise!)

I'm closing this one up - if you have questions or want to discuss recommended deployment or module config, please reopen!

**Comment by brandonsturgeon** [comment]
@neronmoon 
This seems to start working really well!

However, once it tries to start Will again it'll error out with `AttributeError: 'module' object has no attribute 'TEMPLATE_DIRS'` 

Seems like some weirdness going on when trying to reload the settings. Any ideas? 

Thanks so much!

**Comment by neoascetic** [comment]
@brandonsturgeon #107 is related

**Comment by brandonsturgeon** [comment]
In case anyone looks back on this, I've set up an OK solution for now.

I have Will running in a screen session with environment variables set. I have a small Flask server running alongside it that takes a `/restart_the_will_bot` type route. This route finds the `run_will.py` with the lowest PID (this will be the main process) and runs `kill SIGINT {id}` which will gracefully shut down Will and threads. I add a small `time.sleep` to give it time to shut down properly.

The script then sends commands to the screen (using `screen -S {screen_name} -X stuff {command}`) to `git pull origin master` (pulls in the changes I just pushed), runs another `time.sleep` to make sure the pull finishes, then sends a `./run_will.py` command to restart will.

This works very well, I just message my robot to `update plugins` and it'll restart and even let me know when he comes back!

Sidenote, sending commands to a screen session is weird. The `stuff` arg allows you to stuff commands into the STDIN of the screen session, but then you have to send the "enter" key. Here's my piece of code to run commands to Screen session.

```
def issue_command(command):
    """ Issues a command to the running jarvis screen """
    execute_command = ["screen", "-S", "will_screen", "-X", "stuff", "{}\015".format(command)]
    print execute_command

    do_it = subprocess.check_output(execute_command)
    print do_it
```
