### ISSUE TITLE
Using html=True breaks @-ing

### ISSUE THREAD

**Issue by iggyvolz** [skoczen/will#134]
Using html=True with a message gives this:
![image](https://cloud.githubusercontent.com/assets/2197376/7506406/91319284-f42d-11e4-8fea-95e8bb5e89ef.png)
This is probably more of a HipChat bug than a Will one, but it's annoying nonetheless.  Possible solutions could be just to leave the @-ing out for html=True, or doing something like @iggyvolz Coming right up! before saying the message.

**Comment by skoczen** [comment]
Hey,

Yep, unfortunately, that's a known part of the hipchat HTML spec.  None of the built-in magic works - emoticons, `/` messages, etc.

I'm probably a -0.5 about coding will around their specs - I tend to think it's clearer if he matches up cleanly.

The way we handle it is to just `self.say()` two messages, one with the HTML and one with the mention, if it's critical that someone gets an offline ping.  (For direction "hey will, do X for me", we've largely dropped the `@mention` replies.)

**Comment by skoczen** [comment]
Hey @iggyvolz , closing this up as I believe we've got as good a solution as we're going to get now.  Please re-open if you have other ideas!
