### ISSUE TITLE
using will in linked docker container

### ISSUE THREAD

**Issue by odedpr** [skoczen/will#138]
Hi, 

I'm trying to deploy "will" using a docker container, 
I'm using the following : 

Dockerfile :

-----
FROM python:2.7.9
WORKDIR /tmp
RUN pip install will && \
	generate_will_project
CMD ["run_will.py"]

------

linked [redis] (https://registry.hub.docker.com/_/redis/) container.

the problem is that I cannot pass to  "will" the redis link as an argument as it is automatically generated when linking the container, for e.g. : 
REDIS_PORT_6379_TCP=tcp://172.17.0.24:6379

it would be great if  could pass the arguments to the "./run_will.py" script.

**Comment by skoczen** [comment]
Hey @odedpr , 

You can also put any configuration in `config.py`.   In this case, you could do something like,

```python
import os
REDIS_URL=os.environ['REDIS_PORT_6379_TCP']
```

Does that help?

**Comment by odedpr** [comment]
that helped ... 

I used 

REDIS_URL=os.environ['REDIS_PORT_6379_TCP'].replace('tcp','redis')

**Comment by skoczen** [comment]
Great to hear!  Closing this up, then - reopen if you've still got troubles!
