### ISSUE TITLE
New will install, getting not valid user error

### ISSUE THREAD

**Issue by nessenj** [skoczen/will#139]
Brand new will install, attempting to get it connected, however it appears that my username is being chopped up:

in my config.py:

USERNAME="XXXXXX_2148975"

however, when I run will and it attempts to authenticate, some stuff is missing:

ERROR: We ran into trouble: 'Target user 214897 is not a valid user' (the last digit is missing, and the 6 digits with the _ is missing too)

What did I miss?

**Comment by skoczen** [comment]
Hey @nessenj ,

Couple of things:
1. You should keep username and other sensitive data [in environment variables](http://skoczen.github.io/will/config/), not config.py.
2. The username should be the full hipchat username, like ` 12345_123456@chat.hipchat.com`

Let me know if that fixes it!

**Comment by nessenj** [comment]
Hi @skoczen,

Thanks for the response.  I am using env variables, I was trying different things to see if I had a typo, but looks like I left off a big part of the username.  I tested this morning and all is well!  Thanks for the quick response!

**Comment by skoczen** [comment]
@nessenj Hooray! Great to hear!  Always feel free to open an issue if you run into other snags.

If you've got suggestions on how to make the documentation clearer as well, they're welcome!
