### ISSUE TITLE
Documentation / Examples for using HipChat API with will

### ISSUE THREAD

**Issue by nessenj** [skoczen/will#142]
I am writing some code that i'd like to do a few things:

1. have will create a new hipchat room based on a command
2. join that room
3. leave the room and delete the room based on another command

That being said, is there any documentation/examples around that reference using the HipChat API for doing some of these?

**Comment by skoczen** [comment]
Hey @nessenj ,

Hipchat has docs on their V2 api that are pretty solid.

There's also some discussion and code around this on #36 , which is closed.

In short, the summary has been that for everyone so far, the solution that came with `v0.5` of will just joining every room on start was good enough. There isn't a cost to having him in rooms where nobody talk to him, and thus far, that's been good enough for most folks.

Would that work for your setup?  Or, can you explain your use case in more detail, to see if there's an elegant solution we can come up with?

Thanks!

**Comment by nessenj** [comment]
Sure, here is what I am planning..

I have a main room that he will monitor, our noc employees will interface with him there and whatever.  In the event that a critical incident occurs, I would like the noc tech to be able to tell will to start a new hipchat room and the following happens:

1. will creates the room via HipChat's API
2. he then joins the room
3. noc staff can interact with him for the duration of that particular incident (I am writing my version of will to be a data collector).
4. (If possible) - have him log the room to the filesystem
5. when the noc staff determines the critical incident is over, they can issue a command and will closes down the room (again using the API) and saves the chat log.

The way we do things now is we run multiple incidents from a single room and it's a pain in the neck, I would like to give folks a more automated solution.

Make sense?

**Comment by skoczen** [comment]
@nessenj  - That helps a lot, thanks!

How many rooms would you guess you'll need concurrently?

If it's less than say 10, an easy solution would be to make 10 rooms (name them colors or trees or whatnot), have will join all of them, and then when events come up, they can be assigned to one of the existing rooms, and appropriate notifications can be sent out.

`@sally @bill @terrence  "Server on fire, literally on fire" is being handled in ORANGE`

This would save you the trouble of writing log saving, room starting, and join/leave.    You could still set up will to archive chat logs between a given time frame, (writing to disk won't be a problem), or by any other criteria you'd choose.

The choice of room would be an easy plugin to write: `@will new incident server on fire`, and `@will orange resolved`, etc.

Thoughts?

**Comment by nessenj** [comment]
Sorry for the delay in responding, i was out of town for the long holiday...

I would imagine that we wouldn't need more than 5 rooms concurrently.  My original plan was to create/close rooms on the fly, but I think I am swaying towards the idea of having the rooms pre-setup and then using topics to set a short description of the issue that's going on.

I love the idea of notifications being sent out!  That's a plus!

The logging is super important to us, so as long as I can capture data, then life is good :)

**Comment by skoczen** [comment]
Hey @nessenj ,

No worries at all - hope your holiday was a good one!

Glad to hear that the pre-set rooms could work for your setup.

Take a look at the docs for [accessing the room history](http://skoczen.github.io/will/plugins/builtins/#getting-a-rooms-history) and [setting the topic](http://skoczen.github.io/will/plugins/reply/#set-the-topic) and let me know if you see anything else you need! 

-Steven

**Comment by skoczen** [comment]
Hey @nessenj , closing this up since it seems like we have a working solution.  Please re-open if I have that wrong!
