### ISSUE TITLE
The enabling of individual plugins appears to be broken

### ISSUE THREAD

**Issue by Regner** [skoczen/will#144]
This is what I have in my config:

PLUGINS = [
    # Built-ins
    "will.plugins.admin",
    "will.plugins.chat_room",
    "will.plugins.help",
    "will.plugins.productivity.images",

```
# All plugins in your project.
"plugins",
```

]

Will starts up fine, everything seems to be working, but the images plugin is not working.

It works for blacklisting however.

**Comment by skoczen** [comment]
Hey @Regner ,

Thanks for this report!

That makes sense, since the plugins are modules, but it also seems like it shouldn't work that way.  Will take a look on my next sprint - a PR is welcome!

**Comment by ptomkiel-oktawave** [comment]
Isn't this already solved? ;)

**Comment by skoczen** [comment]
@ptomkiel-oktawave  Honestly, I don't remember. :)   Are you still seeing it?

**Comment by ptomkiel-oktawave** [comment]
Nope, it works as expected. IMHO - this issue can be safely closed ;)

**Comment by skoczen** [comment]
Great, @ptomkiel-oktawave  thanks for the confirmation!
