### ISSUE TITLE
Upgrade requirements, python 3 compatibility.

### ISSUE THREAD

**Issue by skoczen** [skoczen/will#149]
It's time.  See #148.

**Comment by mattdeboard** [comment]
Hi, any projections on when this might be a thing?

**Comment by skoczen** [comment]
Not offhand, sadly.  I've been pretty slammed, and am hoping time frees up for will in the next month or so.  However, that time is going to first go into existing PRs, then Slack support, and finally a look at supporting both Py3 and 3. 

If someone wants to put together a PR that adds Py3 support, I'm all ears, and in support!

**Comment by mattdeboard** [comment]
No prob, thanks for update.
