### ISSUE TITLE
Slack Support

### ISSUE THREAD

**Issue by skoczen** [skoczen/will#150]
In the long run, Slack vs. Hipchat is going to look at lot like Github vs Bitbucket.   Will's not going to go away just because Hipchat is run by Atlassian. :)

https://api.slack.com/

**Comment by ShawnMilo** [comment]
:+1: 

I'm willing to help out. If someone more familiar with the project creates some bite-sized sub-issues, I'm up for taking some on.

**Comment by skoczen** [comment]
Cool.  I'd expect to knock out an overall view of `ChatServiceBackend`, and how I'd see this evolving in the next couple weeks.  If people have thoughts, feel free to throw them in on this issue - we'll keep this as the canonical spot for the work.

**Comment by ShawnMilo** [comment]
@skoczen Any progress on planning this? I'm new to contributing to Will, so I'll need some direction in getting started. I really want to see progress on this, because we use HipChat for work and I hate it. ^_^

Just let me know where to start reading, and/or assign a couple of issues to me and I'll get started and ask for help as needed.

**Comment by brandonsturgeon** [comment]
Definitely on board with the transition to Slack. I'm afraid my work is going to move to Slack, and I'll have to rush to move my Will plugins over. Not looking forward to that. I'll jump in if I see something I'm able to do.

**Comment by ShawnMilo** [comment]
@brandonsturgeon Why aren't you looking forward to it, other than the porting? I use both daily and I love Slack and hate HipChat. Even if just for the ability to put `code snippets inline` and _type in italics` it's so much nicer than HipChat.

**Comment by brandonsturgeon** [comment]
@ShawnMilo Oh, I have nothing against Slack, it's just that I have my Will bot all custom made and running smoothly. I just don't want to have to go through every script I have and port it, that's all.

**Comment by skoczen** [comment]
@brandonsturgeon if I do this properly, the only thing you'll have to change is a couple config settings. :)

@ShawnMilo - Thanks for checking in.  I'm pretty slammed for the rest of this month (launching a ~6mo project), so won't have time to dig in until then, really.

However, if you've got free cycles, here's what would help:

I have a good idea of how I want to architect this, but am entirely blind as to what capabilities we have from slack.  All of the following would be really useful, either as links to docs for me to read, or  answers (with links, ideally)

- What do we have in terms of real-time messaging API?  Is there an XMPP interface, or is it strictly over HTTP?
- How does authentication work?
- Are HTML messages supported, and what if any differentiation from plain text is there? (For both read and write)
- API for changing room topics?
- Join/leave API?
- Roster / list of members API?
- How do handles work?
- Are there any other APIs/behaviors that hipchat doesn't support, that would be nice to have in will?

I know doc/research stuff isn't as fun as writing code, so I totally understand if you want to give this a miss. However, it's the next step in getting this built, so if you (or anyone else) does have the time and energy, it's greatly appreciated!

Thanks!
-Steven

**Comment by ShawnMilo** [comment]
Sure. I'll look into that stuff. I'm not very familiar with Will. Does that make me a bad candidate for it? If not, are there any docs/code within Will you recommend I look at so I know what you're trying to find analogs for?

**Comment by skoczen** [comment]
Nope, I think you'll be all good on that front.  

The big stuff he does is listen to an XMPP stream, and the listeners above.  In short, he needs some way to hear messages and send messages.  The richer the data with them, and more real-time they are, the better.

We're not locked into anything - the message listen-y parts are going to be abstracted out into backends anyhow, so however slack does it is fine, and useful.

**Comment by ShawnMilo** [comment]
> What do we have in terms of real-time messaging API? Is there an XMPP interface, or is it strictly over HTTP?

https://api.slack.com/rtm

----

> How does authentication work?

[oauth](https://api.slack.com/docs/oauth)

----

> Are HTML messages supported, and what if any differentiation from plain text is there? (For both read and write)

No. A [subset of markdown](https://api.slack.com/docs/formatting) is supported.

----


> API for changing room topics?

[yes](https://api.slack.com/methods/channels.setTopic)

----


> Join/leave API?

[join](https://api.slack.com/methods/channels.join)

[leave](https://api.slack.com/methods/channels.leave)

----

> Roster / list of members API?

The [accessLogs](https://api.slack.com/methods/team.accessLogs) call returns
a list of users with information about their login history.

----

> How do handles work?

Please elaborate.

----

> Are there any other APIs/behaviors that hipchat doesn't support, that would be nice to have in will?

I'll have to do more research into HipChat's API to answer that.

----

# Other notes:

Special comments on [bot users](https://api.slack.com/bot-users)

Mostly about how they're free, but can't log into the Web portal. Also
some limitations on API functionality.

**Comment by ShawnMilo** [comment]
Let me know if you have any follow-up questions, and what the next steps are.

**Comment by skoczen** [comment]
Fantastic, will take a look when I get some cycles.  Thanks much!

**Comment by ShawnMilo** [comment]
@skoczen <ping>  :o)

**Comment by skoczen** [comment]
Hey @ShawnMilo, thanks for the ping - thought I got all the open issues.  Thanks for your patience!

- 

Hey, just tossing out a quick note on this and all the other PRs to say thanks for your patience.

Neither will nor your contributions have been forgotten!

We've just launched our app at my day job, and given that I'm currently the entirely of the dev team, finding cycles for open-source work hasn't been possible. Things are settling down though, and I should have a proper block of time at the end of next sprint (end of September.) Thanks for hanging in there!

**Comment by ShawnMilo** [comment]
Hey @skoczen: ping. ^_^

Is there anything I can do?

**Comment by giocalitri** [comment]
I am willing to help with this.

**Comment by skoczen** [comment]
Blegh.  I want this so much, but the time for me to do it just isn't there to be found.  

Alright, let's see what we can do collectively.  Maybe use this thread to talk about architecture, spec out some patterns, and coordinate work?   

It's clear at this point that as much as I'd like to do the coding, it's not happening.  I will have a block to work on it in December, but I never bet on an empty week staying empty.

Broadly, here's how I'd like to see slack integrated.

1. `WillBackend` class created, with clean abstractions for routes, incoming messages and outgoing messages.   Ideally unit tests, too.
2. `HipChatBackend(WillBackend):` created. Re-implements the current codebase, using the backend pattern. Again, ideally with tests.
3.  Test the crap out of that, make sure it's working, and ship a release.  Support that release, and handle any weird edge cases if they come up.
4. Build a `SlackBackend(WillBackend)` class that implements the same methods, for slack.  
5. Doc, test, doc, test some more, and release.

Notes:
- This would also allow folks to write gchat, IRC, etc, but this isn't a priority for this project.
- The backend should be specified in `config` and for now, default to Hipchat.  The same patterns for hipchat sensitive data and API, etc should be followed.
- Finally, we'll need lots of docs with lots of clarity. Config documentation is a weakness right now, and this is a great chance to turn it into a strength.
- With the docs, do proper writeups that make it easy for potential users to find will whether they're on Slack or Hipchat.

Thoughts? 

Thanks for your enthusiasm and your continued pings!  You're what's making this real!

-Steven

**Comment by ShawnMilo** [comment]
Cool. I'm poking at it already -- just exploratory stuff. I'll update when I have questions or progress to report.

**Comment by brandonsturgeon** [comment]
Awesome! When I get a a little bit, I'll see what I can do on this

**Comment by skoczen** [comment]
Cool, I think for everyone, let's start with a spec on what `WillBackend` looks like.  The actual wiring into slack won't be that hard - it's just getting the architecture right and making sure it's stable.

**Comment by skoczen** [comment]
A couple notes:  https://github.com/lins05/slackbot

via https://api.slack.com/rtm

**Comment by ShawnMilo** [comment]
Does this mean Will will stick with its HipChat heritage, and Slackbot can take up the Slack challenge?

Or is an integration in the future? They're both MIT licensed, so it would be possible to join forces.

Incidentally, I've changed jobs and no longer use HipChat or Slack for business purposes. I'm still willing to help out and will continue to watch this thread, but I don't expect to be using Will again myself.

**Comment by Tenzer** [comment]
A benefit of abstracting the communication out to a separate class, is that you easily would be able to make a local test mode for Will, [similar to what Hubot has](https://hubot.github.com/docs/adapters/shell/). That would be convenient when writing plugins instead of having to connect to an actual HipChat server.

**Comment by chillipeper** [comment]
I agree with @Tenzer would be great to be able to test will plugins locally without having to connect to hipchat

**Comment by nhatfield** [comment]
I this a dying issue?? Would love to see this in slack as we've officially switched from hipchat. I would much rather get an updated Will,  than to have to switch to a slack friendly python bot and port everything over. Anything in the works or should we realistically look elsewhere for now, until we can all come up with a working Will-slack solution? Let me know whats left, i wouldnt mind taking a swing at a few tasks

**Comment by skoczen** [comment]
Definitely not a dying issue, I've just been slammed, and not had time to put into will.  Will's definitely still a priority for me - despite the complete dearth of response on both tickets and PRs, and slack support is probably #1 on that list.  Hell, my own company wants to switch from hipchat to slack, we just haven't found the resources.

That said, I probably need to do a much, much better job at delegating, accepting contributions, and giving more people the ability to move Will forward.

Open source.  It's theoretically 90% technical, 10% personal, but the reality is usually the opposite.

I'm very, very open to any and all contributions on Slack support and other PRs.  

Thanks to you and everyone in this and all the other open PRs.  Will isn't getting as much attention right now as he deserves.  But he's not going anywhere.

**Comment by skoczen** [comment]
Also, in that PR-land world,  there are a pretty basic number of things chat bots can do:  hear, talk, talk in a special way.  That's kind of it. 

What I'm looking for for slac  k support is:
1) An abstraction for chat behavior, and 
2) A backwards-compatible hipchat backend written.

Once that's set, we can have slack backends, telegram backends, etc all pretty easily.   I recognize there are some funky bits in the internals of will, but I also think this is less than a week's work.  If anyone, anywhere can spare the cycles, they're very welcome, and I'm more than happy to give any input that's helpful.

**Comment by nhatfield** [comment]
Awesome, appreciate the feedback. I'll see what i can do in my spare time too. Ill be porting over in the interim just because of deadlines, but I'll also work on Will as much as possible!

:cheers:

**Comment by skoczen** [comment]
Noting that this is now working, and being refined over in #258  - closing this up, and please track there!
