### ISSUE TITLE
Does not detect groupchat_message since v0.9

### ISSUE THREAD

**Issue by woohgit** [skoczen/will#153]
Something went wrong during the v0.9 release.

Will does not react for `groupchat_message`, but works flawlessly via 1-1. Not even responding to the `@will ping`.

**Comment by woohgit** [comment]
Looking at the diff between 0.8.2 - master

https://github.com/skoczen/will/compare/0.8.2...master

**Comment by woohgit** [comment]
I think I got it. Hold on. :)

**Comment by skoczen** [comment]
Odd. Worked here in my tests, checking as well!

**Comment by woohgit** [comment]
Interesting, this always returns None when in groupchat, but works for 1-1. Maybe hipchat is sending something differently? That could be as well. On it.

```python
search_matches = l["regex"].search(body)
```

I'll dig a bit deeper into this.

**Comment by skoczen** [comment]
Alright, verified here too - it appears only to be `respond_to`s.   `hear`s are working well for me.

**Comment by skoczen** [comment]
I'm also not seeing the pagerduty plugin be ignored, even though it's in the blacklist. Very strange.

**Comment by skoczen** [comment]
Found the bug on the responds - somehow, we're getting an extra space inserted in body.

**Comment by skoczen** [comment]
Ah. right.

**Comment by skoczen** [comment]
Cool. Got a fix. Want to see if I can knock out this blacklist thing in the next couple minutes too, otherwise will just release this and do that as a separate one.

Thanks for the report!!!

**Comment by skoczen** [comment]
@woohgit ^

**Comment by skoczen** [comment]
Blacklist turns out just to be a path thing between root will and proper installations. Not worth fixing at the moment.

Fix has been deployed as `0.9.1`.

`respond_to` fix appears to be working, just tested on my deployed wills.  If you have a moment to test on your installs, that'd be great - leaving this open until I get external confirmation!

**Comment by woohgit** [comment]
will test it soon. About 30min.

**Comment by skoczen** [comment]
All good. 

BTW, @woohgit , in a small story you (and other core contributors) will enjoy, we recently brought on a new employee at my company. They handle all the billing, payroll, etc - and after about a week, they asked, "So, I don't have any paperwork for this William. Is he on direct deposit?"

Upon being told he was a robot, they were stunned, saying, "but he said good morning, when I told him good morning!" 

:)

**Comment by woohgit** [comment]
I just don't get why we need to strip twice. How that extra space gets there? :)

**Comment by skoczen** [comment]
It's the space between `@will` and the rest of the message. :)

**Comment by skoczen** [comment]
Could also solve it by adding one to the offset above, but the strip is almost as cheap, and seemed saner to me.

**Comment by woohgit** [comment]
Hehe, I loved your story.

**Comment by skoczen** [comment]
Made my week. :)

**Comment by woohgit** [comment]
Anyway sorry about this issue. This was in my PR. Surprisingly for some reason it was working in my branch, but maybe I f@cked up something else :)

Thanks for fixing it.

**Comment by skoczen** [comment]
No sorries needed - these things happen!  

I reviewed that code too, and tested locally, and still missed it.

My big takeaway was that sometime soon, maybe before 1.0, we need to put in some automated tests to catch this kind of stuff.  Will's now too big and too widely used for my and other folks' hand-testing to be our sanity checks.

**Comment by woohgit** [comment]
:+1: for the automated tests. ;)

**Comment by woohgit** [comment]
Ohh, I see why it was working for me. I didn't remove the second strip() in my production branch so it was "OK" for sure. :)

**Comment by skoczen** [comment]
Mystery solved!
