### ISSUE TITLE
issue with regex?

### ISSUE THREAD

**Issue by amitbedajna** [skoczen/will#154]
If I directly write "help" to the will user on hipchat, will responds.
But If I write "@will help" in a room where will is a participant, will does not respond. 
I think I know the reason. 
In help.py, the regex is like: @respond_to("^help").
When I write "@will help" in a room, the server receives a message with body "@will help" and the above regex obviously does not match.
Appreciate if you comment on this design choice.

**Comment by skoczen** [comment]
Hey @amitbedajna ,

Under the hood, all of that is taken care of, and will should respond to `@will help` in a room or just `help` in a 1-1 chat.

There was a bug in 0.9 that was patched by 0.9.1 this morning, that would cause the behavior you're seeing.  Can you confirm what version you're using?

Thanks!
-Steven

**Comment by amitbedajna** [comment]
Hi @skoczen,

Just upgraded to 0.9.1 from 0.9. Now it works as expected. Thanks a lot for the quick response.

Regards,
Amit

**Comment by skoczen** [comment]
@amitbedajna great to hear!  You're one of the unlucky ones to notice - it was only out in the wild for about 12 hours. 

Thanks for your patience, and the quick report!

-Steven
