### ISSUE TITLE
@hear() for a specific channel?

### ISSUE THREAD

**Issue by brandonsturgeon** [skoczen/will#162]
We have a specific channel where anyone can talk to Will, is there any way to have him listen for commands in that channel without looking for an @Will mention?

ps: sorry https://github.com/Will for the poke

**Comment by skoczen** [comment]
Not at present. You can just check the message object though - it will tell you which room the message came in.

**Comment by skoczen** [comment]
Also, unless you need public transcripts, you can always message will in a 1-1, and he'll respond there as if everything was prefaced with an `@will`.

**Comment by brandonsturgeon** [comment]
So I'd have a @listen("(?P<message>.*)") regex and then just check the message? That seems a bit exhaustive. 

And yes, I know he's able to be 1-1'd (super great btw) But it's kind of fun to have a channel where we can all just yell at Will. It'd actually be super helpful to only have it listen to a few specific commands in a specific channel, but I know that's getting a bit more complex.

**Comment by skoczen** [comment]
Doing a big review - closing this up for now, please re-open as a PR if it's something you're interested in writing code for!  Thanks for raising it & discussing!
