### ISSUE TITLE
@route("blah", method=POST) POST is undefined

### ISSUE THREAD

**Issue by brandonsturgeon** [skoczen/will#163]
I'd like to make a route in my plugins that allows a user to post data, but it says POST is undefined. If I try to post to the url without it, I get a 405 Method Not Allowed. Even putting POST in quotes and then trying, I still get the 405 Method Not Allowed

Following this example:
http://skoczen.github.io/will/plugins/notice/#handle-webhooks-and-web-pages

EDIT: This was mostly just me being stupid. POST definitely needs to be in quotes and then it's good to go.

**Comment by skoczen** [comment]
Yep, quotes are def needed - would you mind sending a quick docs PR?  

Thanks for digging in on this one!

**Comment by brandonsturgeon** [comment]
No problem!
