### ISSUE TITLE
Do not fetch room list

### ISSUE THREAD

**Issue by charlax** [skoczen/will#166]
Hi,

When there's a ton of rooms, Will requires using the V1 token.

Would it be possible for Will to not try to fetch all available rooms, but instead just accept a list of Hipchat room id that it can directly connect to? From what I read of the code, `available_rooms` is mainly used to translate a room name to a room id.

**Comment by skoczen** [comment]
Hey @charlax,

Thanks for the reach out and idea!

The longer term fix is to just update to use the v2 token's new rooms request, which will fix the issue.  A pull request is welcome.

Otherwise, it's on my list to get to, and in the meantime, please use a v1 token.

Thanks!

**Comment by charlax** [comment]
It does use the V2 token if it's present, but it limits the number of rooms fetched: https://github.com/skoczen/will/blob/master/will/mixins/room.py#L9

Did you mean that there's a new Hipchat API endpoint for that feature?

**Comment by skoczen** [comment]
Yep, since that code was written, there's now a v2 bulk api.

**Comment by charlax** [comment]
I guess this one? https://www.hipchat.com/docs/apiv2/method/get_all_rooms
