### ISSUE TITLE
Tests

### ISSUE THREAD

**Issue by michaeljoseph** [skoczen/will#17]
And maybe a `CONTRIBUTING.md` with style guides and conventions?

**Comment by sivy** [comment]
:+1:  as I'd love to be able to write tests for our own plugins as well

**Comment by sivy** [comment]
I'd even be willing to help with will's tests if the framework is sound.

**Comment by skoczen** [comment]
Just a note here that there is a basic test framework in place now (it came in with the talkbackbot port), and if anyone wants to jump on / expand, you're welcome to!

**Comment by skoczen** [comment]
Closing this up, as we've got a functioning start, and plugins can now be tested!
