### ISSUE TITLE
Any chance of improving Will's time parsing?

### ISSUE THREAD

**Issue by brandonsturgeon** [skoczen/will#170]
Right now if we want a reminder, we'd do `@will remind me to do ACTIVITY at 5:00pm` which works well and all, but what if we could do `@will remind me to do ACTIVITY in 30 minutes` 

I'll look into this tonight unless someone has any reason why I shouldn't.

**Comment by woohgit** [comment]
The PR [155](https://github.com/skoczen/will/pull/155) enables the `in` parsing as well.

**Comment by skoczen** [comment]
+1, and it's going in on my next sprint - thanks for your patience, all!

**Comment by skoczen** [comment]
Closing since #155 is merged, and going out for release!
