### ISSUE TITLE
Enable Will to delete an schedule_say

### ISSUE THREAD

**Issue by ayashjorden** [skoczen/will#171]
Hi,
Is there a way to delete a schedule_say?
I ran into this use-case while I set will to announce "24 hours since last error...", but then an error occurred and there is no API to cancel the scheduled message.

Hope it's clear enough...

Thanks,
Yarden

**Comment by skoczen** [comment]
Hey @ayashjorden , 

Completely clear, thanks for submitting an issue and raising the question!

At the moment, you'd have to manually delete it from the redis store.  It's very definitely not ideal, but has been so rare that nobody's written a good interface to it.

One's welcome if you're interested in writing it - if not, no worries.

-Steven

**Comment by skoczen** [comment]
Closing this up - please re-open if you're interested in submitting a PR!
