### ISSUE TITLE
Instructions for setting up automated tests

### ISSUE THREAD

**Issue by shadow7412** [skoczen/will#175]
I'd like to have the automated tests work in my fork of will.
https://travis-ci.org/shadow7412/will

Would it be possible to add somewhere the minimum required setup for this to work? That way it'd be easier to encourage people to add tests when they do pull requests....

**Comment by skoczen** [comment]
Hey @shadow7412 ,

I'm a +1 to that.  For the moment, the closest we have is that there are both circle.yml and .travis files in the repo - those can get you unstuck at least.

Leaving this issue open, as better and clearer test support is something we definitely want.

PRs are welcome if you're interested!

**Comment by skoczen** [comment]
Hey @shadow7412 ,

I've just updated the travis.yml to be good on the latest build - the only thing that's missing is that users need to set the environment variables.

I've also plugged my CircleCI setup in, so all future PRs should automatically have tests run and visible.

Closing this up, as I think this fixes it - if not, please reopen!

-Steven
