### ISSUE TITLE
'hear' for specific user

### ISSUE THREAD

**Issue by ayashjorden** [skoczen/will#176]
Hi,
How can I tell Will to listen for messages from specific member ?

Thanks,
Yarden

**Comment by skoczen** [comment]
Hi @ayashjorden ,

The simplest way is to have people send 1-1 messages directly to will.  However, if to restrict will to just listening to certain people for certain messages, take a look at the [access control](http://skoczen.github.io/will/plugins/builtins/#access-control) functionality.  It should do what you need.

Let me know if that doesn't hit it!

-Steven

**Comment by brandonsturgeon** [comment]
Another option is to have an @hear, and then do a check to make sure it's the user you want to listen from.

````
@hear("test message")
def hear_test_from_user(self, message):
    if message.sender["mention_name"] != "Persons_Mention_Name":
        return False
    self.say("Correct user!", message=message, color='green')
```

**Comment by skoczen** [comment]
FWIW, that's basically what the access control stuff does, but keeps it DRY, and future proof.  Unless you only have one function, I'd use the ACLs.

**Comment by skoczen** [comment]
Closing this up - if you're still stuck, please reopen with more details!
