### ISSUE TITLE
Mention by user's email

### ISSUE THREAD

**Issue by ayashjorden** [skoczen/will#179]
Hi,
I'm integrating our deploy process to notify users about deploy events.
I only have the user's email in scope when I invoke Will's API.

Is there any function to get user's mention name by email?

Thanks,
Yarden

**Comment by woohgit** [comment]
Yes, you can do that, although there isn't any implemented function in will for that atm, so you have to implement it yourself.

If you look at https://github.com/skoczen/will/blob/master/will/mixins/hipchat.py#L13

https://api.hipchat.com/v2/user?auth_token=xxx

You just need to play with these things with the internal_rooster. :)

PRs are welcome :)

**Comment by skoczen** [comment]
+1 to @woohgit 's response.

One note/caveat:  using the hipchat API assumes that all users you're passing in have accounts with hipchat, using the same email address that is set up in their hipchat account.  I can imagine that not being true in a lot of cases.

If yours is one of them, a simple fix is to keep an email/handle mapping either in your source files (if it's a small team), in will's storage (if you want to configure via chat), or in a JSON file sitting on your server.

In any case, if you come up with a general solution, a PR would be most welcome!

**Comment by skoczen** [comment]
Closing this up for now - please reopen if you're up to submit a PR!
