### ISSUE TITLE
Link to APScheduler links to a dead page

### ISSUE THREAD

**Issue by brandonsturgeon** [skoczen/will#185]
http://skoczen.github.io/will/plugins/notice/

"Under the hood, @periodic uses apscheduler to provide its options, so you can use any of the following as keyword arguments:" (Sorry for the ping @ periodic)

Links to http://apscheduler.readthedocs.org/en/latest/cronschedule.html#available-fields which appears to be dead.

There is this page for documentation https://apscheduler.readthedocs.org/en/latest/ we could use. Not sure what we should point to instead.

https://apscheduler.readthedocs.org/en/v2.1.2/cronschedule.html

There's a link to good examples, but it's for an older version of the library.

**Comment by skoczen** [comment]
Hey @brandonsturgeon ,

Thanks for this - your second link ( https://apscheduler.readthedocs.org/en/v2.1.2/cronschedule.html ) is what it should be. Will get this in with the next release!

-Steven

**Comment by skoczen** [comment]
Fixed in 0.9.4 docs!
