### ISSUE TITLE
ACL strange behaviour

### ISSUE THREAD

**Issue by AndrewBurdyug** [skoczen/will#186]
Hi! 

Why you "lowerize" the nicks?

will/acl.py:

``` python

def is_acl_allowed(nick, acl):
    nick = nick.lower()
    for a in acl:
        acl_members = get_acl_members(a)
        if nick in acl_members:
            return True

    return False
```

My mention name in hipchat is "AndrewBurdyug" (default mention name during the sign up process), my colleges also have their hipchat mention names in CamelCase, 
it's comfortable for us, as I think for many others too. 

Due to your **nick = nick.lower()** I should create my ACL in lower case,  it is not obvious!

**Comment by AndrewBurdyug** [comment]
There are any comments?

**Comment by skoczen** [comment]
This slipped through my radar, thanks for your patience.

I'll have to dig into the acl code to see if there's a reason behind this (it's a bit foreign as it came in via a PR,) but what you're raising certainly seems reasonable to me.

Will dig into this on my next sprint - if you have time in between to dig in and submit a PR, one's welcome!

**Comment by AndrewBurdyug** [comment]
Thanks!

**Comment by woohgit** [comment]
ACL was written by me.

The lowercase is for purpose. The ACL members should written in lowercase. I don't want to keep in mind how people are capitalize their names. (My name is WoOh for example and nobody is able to write it correctly..) Wo0h, woOh, WooH, Wooh, but never: WoOh... 

You don't need to change your Mention name, but you need to change the ACL only, so the ACL definitions should contain lowercase definitions. That's all.

**Comment by skoczen** [comment]
Any opposition to just `.lower()`ing names for comparison, and allowing any mix of case?

**Comment by woohgit** [comment]
I'll send a PR with both .lower() and original name comparison. So that would fix this and also keep the lower() compatibility as well.

**Comment by brandonsturgeon** [comment]
Hey @woohgit !

Were you able to find a solution to this?

**Comment by woohgit** [comment]
@brandonsturgeon sure, I sent a PR, but it's till unmerged, Skoczen actually working on his own life ( writing books etc) so he hasn't merging things. Last release was in 2015. ;/

**Comment by brandonsturgeon** [comment]
@woohgit Right, I just wanted to check up on it. I scanned through the PRs but didn't see one relating to this. Must've missed it.

**Comment by woohgit** [comment]
@brandonsturgeon maybe forgot to send it, because I was sure that nobody will merge it :)

Here is the branch: https://github.com/woohgit/will/commits/loosenig_acl_ignore_case

**Comment by skoczen** [comment]
@woohgit Not that it necessarily helps, but I do see every comment and PR, and am still working hard to figure out how to carve out time for will.   I've put this out before, but if there are folks who are interested in helping share the load, I'm open to it.

**Comment by skoczen** [comment]
@woohgit want to send that over as a PR?  Somebody will merge it :)

**Comment by woohgit** [comment]
I'm currently in a hospital for about 2 months, but from next week I'll be able to do things :) stay tuned.

**Comment by skoczen** [comment]
@woohgit yikes!!!  Still in Japan?  Sounds like things have taken a turn! 

Staying tuned, and get better!

**Comment by skoczen** [comment]
@woohgit Ping on this - can you send a PR of the case-loosening?  Thanks!

**Comment by woohgit** [comment]
@skoczen I think this can be closed.

**Comment by skoczen** [comment]
@woohgit closing it up then!  This is all working here as well.
