### ISSUE TITLE
Will could not respond any messages at a Hipchat room (will 0.9.3)

### ISSUE THREAD

**Issue by kwailamchan** [skoczen/will#187]
I set up WILL_ variables and run_will.py, it was reported "will is running", but when I typed a message in a hipchat room, nothing responded. Is there anything I am missing?
- will: 0.9.3

config.py

```
export WILL_USERNAME="jabber id"
export WILL_PASSWORD="password"
export WILL_V2_TOKEN="v2 token (scope: view group)"
export WILL_V1_TOKEN="admin token"

export HIPCHAT_SERVER="chat.hipchat.com"
export WILL_REDIS_URL="redis://localhost:6379/7"
export WILL_HELLO_MESSAGE="Hello from will"
```

run_will.py

<pre><code>
      ___/-\___
  ___|_________|___
     |         |
     |--O---O--|
     |         |
     |         |
     |  \___/  |
     |_________|

      Will: Hi!

Verifying environment...
  ✓ WILL_USERNAME
  ✓ WILL_PASSWORD
  ✓ WILL_V2_TOKEN
  ✓ WILL_REDIS_URL

Verifying credentials...
  ✓ will authenticated
  ✓ @Will verified as handle

Loading configuration...
  Importing config.py...
    ✓ Valid.
  Verifying settings...
    - Note: REDIS_MAX_CONNECTIONS not set. Defaulting to 4.
    ✓ ALLOW_INSECURE_HIPCHAT_SERVER
    ✓ ADMINS
    ✓ DEFAULT_ROOM
    ✓ HELLO_MESSAGE
    ✓ HTTPSERVER_PORT
    ✓ HANDLE
    ✓ HIPCHAT_SERVER
    ✓ NAME
    ✓ PLUGIN_BLACKLIST
    ✓ PLUGINS
    ✓ PASSWORD
    ✓ PUBLIC_URL
    ✓ REDIS_URL
    ✓ REQUESTS_OPTIONS
    ✓ REDIS_MAX_CONNECTIONS
    ✓ ROOMS
    ✓ STORAGE_BACKEND
    ✓ TEMPLATE_DIRS_PICKLED
    ✓ USE_PROXY
    ✓ USERNAME
    ✓ V1_TOKEN
    ✓ V2_TOKEN

Bootstrapping storage...
  ✓ Bootstrapped!

Bootstrapping plugins...

  Administrative actions ------------------------------------------------ will.plugins.admin
    ✓ KeepAlive
    ✓ Storage
    ✓ Version
    ✓ Ping
    ✓ Say

  Hipchat actions --------------------------------------------------- will.plugins.chat_room
    ✓ Rooms
    ✓ NewTopic
    ✓ Roster

  Devops, server stuff, and uptime ------------------------------------- will.plugins.devops
    ✗ PagerDuty (blacklisted)
    ✓ HerokuIsUp
    ✓ EmergencyContacts
    ✓ HipChatIsUp
    ✓ GithubIsUp

  Old-fashioned friendliness ----------------------------------------- will.plugins.friendly
    ✓ Thanks
    ✓ MorninEvenin
    ✓ ItsLove
    ✓ RandomTopic
    ✓ TalkBack
    ✓ Snickerdoodles
    ✓ Hello

  It can't all be about work! --------------------------------------------- will.plugins.fun
    ✓ GooglePoem
    ✓ Pug

  Help ------------------------------------------------------------------- will.plugins.help
    ✓ ProgrammerHelp
    ✓ Help

  Plugins -------------------------------------------------------------------------- plugins
    ✓ Hello

  Productivity --------------------------------------------------- will.plugins.productivity
    ✗ Hangout (blacklisted)
    ✗ Time (blacklisted)
    ✓ Remind
    ✓ Images
    ✗ Bitly (blacklisted)

  Web pages --------------------------------------------------------------- will.plugins.web
    ✓ HomePage

Verifying settings requested by plugins...
  ✓ PUBLIC_URL

Bootstrapping complete.

Starting core processes:
  ✓ Web server started.
  ✓ Scheduler started.
  ✓ Chat client started.
  ✓ Will is running.

</code></pre>

**Comment by skoczen** [comment]
What I'm not seeing are any rooms joined in the output.  Are you using the regular hipchat server or a private one?  Also, what's your `ROOMS` variable in the config look like?

Thanks!
-Steven

**Comment by KellyChan** [comment]
@skoczen Thanks for your prompt reply.

I have two config files, one is private config with hipchat account and token (regular server: hipchat.com) as shown above. 
Another one is the regular config.py.

config.py with rooms setting

<pre>
 87 # ------------------------------------------------------------------------------------
 88 # Optional settings
 89 # ------------------------------------------------------------------------------------
 90
 91 # The list of rooms will should join.  Default is all rooms.
 92 ROOMS = ['Testing', 'Octowill',]
 93
 94
 95 # The room will will talk to if the trigger is a webhook and he isn't told a specific room.
 96 # Default is the first of ROOMS.
 97 DEFAULT_ROOM = 'Octowill'
</pre> 

Thanks,
Kelly

**Comment by skoczen** [comment]
Hey Kelly,

So I'm a bit confused - your config.py above (at the top) isn't python syntax, but environment variables.  Just making sure that you're actually setting that in the environment.

The catch is somewhere in your `ROOMS`.  Can you try just commenting it out entirely (will will try to join all rooms by default).

Here's the output you're looking for, with rooms:

```bash
$ ./run_will.py 

      ___/-\___
  ___|_________|___
     |         |
     |--O---O--|
     |         |
     |         |
     |  \___/  |
     |_________|

      Will: Hi!


Verifying environment...
  ✓ WILL_USERNAME
  ✓ WILL_PASSWORD
  ✓ WILL_V2_TOKEN
  ✓ WILL_REDIS_URL

Verifying credentials...
  ✓ William T Botterton authenticated
  ✓ @will verified as handle

Loading configuration...
  Importing config.py... 
    ✓ Valid.
  Verifying settings... 
    ! Warning: no ROOMS list found in the environment or config.  This is ok - Will will just join all available rooms.
    - Note: REDIS_MAX_CONNECTIONS not set. Defaulting to 4.
    ✓ ALLOW_INSECURE_HIPCHAT_SERVER
    ✓ ADMINS
    ✓ DEFAULT_ROOM
    ✓ EMAIL
    ✓ HANGOUT_URL
    ✓ HTTPSERVER_PORT
    ✓ HIPCHAT_SERVER
    ✓ HANDLE
    ✓ NAME
    ✓ PLUGINS
    ✓ PLUGIN_BLACKLIST
    ✓ PASSWORD
    ✓ PUBLIC_URL
    ✓ REDIS_URL
    ✓ REQUESTS_OPTIONS
    ✓ REDIS_MAX_CONNECTIONS
    ✓ ROOMS
    ✓ STORAGE_BACKEND
    ✓ TEMPLATE_DIRS_PICKLED
    ✓ TOKEN
    ✓ USERNAME
    ✓ URL
    ✓ USE_PROXY
    ✓ V2_TOKEN
    ✓ WORLD_WEATHER_ONLINE_KEY
    ✓ os

Verifying rooms...
  ✓ Joining all 3 known rooms.

Bootstrapping storage...
  ✓ Bootstrapped!

Bootstrapping plugins...
  
  Administrative actions ------------------------------------------------ will.plugins.admin
    ✓ Version
    ✓ Say
    ✓ Storage
    ✓ Ping
    ✓ KeepAlive
  
  Hipchat actions --------------------------------------------------- will.plugins.chat_room
    ✓ Roster
    ✓ NewTopic
    ✓ Rooms
  
  Devops, server stuff, and uptime ------------------------------------- will.plugins.devops
    ✓ HerokuIsUp
    ✓ EmergencyContacts
    ✓ BitBucketIsUp
    ✓ HipChatIsUp
    ✓ GithubIsUp
    ✗ PagerDuty (blacklisted)
  
  Old-fashioned friendliness ----------------------------------------- will.plugins.friendly
    ✓ MorninEvenin
    ✓ RandomTopic
    ✓ Snickerdoodles
    ✓ Thanks
    ✓ ItsLove
    ✓ Hello
    ✓ TalkBack
  
  Help ------------------------------------------------------------------- will.plugins.help
    ✓ Help
    ✓ ProgrammerHelp
  
  Plugins -------------------------------------------------------------------------- plugins
    ✓ ItsLove
    ✓ RedFlags
    ✓ Sleep
    ✓ Say
    ✓ TimeTopic
    ✓ FunImages
    ✓ HeyWill
    ✓ Hello
    ✓ Birthday
    ✓ OneThing
    ✓ Uptime
    ✓ Train
    ✓ OneThing
    ✓ MonthlyGoals
    ✓ Nest
    ✓ Walkmaster
    ✓ ChangeMonsters
  
  Productivity --------------------------------------------------- will.plugins.productivity
    ✓ Hangout
    ✓ Remind
    ✗ Bitly (blacklisted)
    ✓ Time
    ✓ Images
  
  Web pages --------------------------------------------------------------- will.plugins.web
    ✓ HomePage

Verifying settings requested by plugins...
  ✓ PUBLIC_URL
  ✓ HANGOUT_URL
  
Bootstrapping complete.

Starting core processes:
  ✓ Web server started.
  ✓ Scheduler started.
  ✓ Chat client started.
  ✓ Will is running.
```

**Comment by KellyChan** [comment]
Hi Steven,

I created a new environment and re-generated will project, and then
- set up WILL_USERNAME, WILL_PASSWORD, WILL_V2_TOKEN as environment variables
- set up PUBLIC_URL = "http://localhost:9000" and HTTPSERVER_PORT = "9000" in config.py
- run `./run_will.py`
- went to hipchat.com, login with another user account, it was shown that `Kelly` (my will account) was online
- with another user account, typed `@Kelly hi` in a chat room, nothing happened.

Reviewed the config variables, the scope of `WILL_V2_TOKEN` is  `view group`.

Compared the outputs with yours provided, `Verifying credentials...` is different,  my will account is `Kelly` and yours is separated as `William T Botterton` and `@will`. Do I need to config will at hipchat?

Yours:
<pre>
Verifying credentials...
  ✓ William T Botterton authenticated
  ✓ @will verified as handle
</pre>

Mine:
<pre>
Verifying credentials...
  ✓ Kelly authenticated
  ✓ @Kelly verified as handle
</pre>

Here was the full output:

<pre>

      ___/-\___
  ___|_________|___
     |         |
     |--O---O--|
     |         |
     |         |
     |  \___/  |
     |_________|

      Will: Hi!


Verifying environment...
  ✓ WILL_USERNAME
  ✓ WILL_PASSWORD
  ✓ WILL_V2_TOKEN
  ✓ WILL_REDIS_URL

Verifying credentials...
  ✓ Kelly authenticated
  ✓ @Kelly verified as handle

Loading configuration...
  Importing config.py...
    ✓ Valid.
  Verifying settings...
    ! Warning: no ROOMS list found in the environment or config.  This is ok - Will will just join all available rooms.
    - Note: WILL_REDIS_URL not set.  Defaulting to redis://localhost:6379/7.
    - Note: REDIS_MAX_CONNECTIONS not set. Defaulting to 4.
    ! Warning: no V1_TOKEN found in the environment or config.This is generally ok, but if you have more than 30 rooms, you may recieve rate-limit errors without one.
    ✓ ADMINS
    ✓ ALLOW_INSECURE_HIPCHAT_SERVER
    ✓ HANDLE
    ✓ HTTPSERVER_PORT
    ✓ HIPCHAT_SERVER
    ✓ NAME
    ✓ PUBLIC_URL
    ✓ PLUGIN_BLACKLIST
    ✓ PASSWORD
    ✓ PLUGINS
    ✓ REDIS_URL
    ✓ REDIS_MAX_CONNECTIONS
    ✓ ROOMS
    ✓ REQUESTS_OPTIONS
    ✓ STORAGE_BACKEND
    ✓ TEMPLATE_DIRS_PICKLED
    ✓ USERNAME
    ✓ USE_PROXY
    ✓ V2_TOKEN

Verifying rooms...
  ✓ Joining all 2 known rooms.

Bootstrapping storage...
  ✓ Bootstrapped!

Bootstrapping plugins...

  Administrative actions ------------------------------------------------ will.plugins.admin
    ✓ Version
    ✓ KeepAlive
    ✓ Ping
    ✓ Storage
    ✓ Say

  Hipchat actions --------------------------------------------------- will.plugins.chat_room
    ✓ NewTopic
    ✓ Rooms
    ✓ Roster

  Devops, server stuff, and uptime ------------------------------------- will.plugins.devops
    ✓ HerokuIsUp
    ✓ HipChatIsUp
    ✓ GithubIsUp
    ✓ BitBucketIsUp
    ✗ PagerDuty (blacklisted)
    ✓ EmergencyContacts

  Old-fashioned friendliness ----------------------------------------- will.plugins.friendly
    ✓ TalkBack
    ✓ ItsLove
    ✓ Snickerdoodles
    ✓ Hello
    ✓ RandomTopic
    ✓ Thanks
    ✓ MorninEvenin

  It can't all be about work! --------------------------------------------- will.plugins.fun
    ✓ Definition
    ✓ GooglePoem
    ✓ Pug

  Help ------------------------------------------------------------------- will.plugins.help
    ✓ ProgrammerHelp
    ✓ Help

  Plugins -------------------------------------------------------------------------- plugins
    ✓ Hello

  Productivity --------------------------------------------------- will.plugins.productivity
    ✗ Bitly (blacklisted)
    ✓ Images
    ✗ Hangout (blacklisted)
    ✗ Time (blacklisted)
    ✓ Remind

  Web pages --------------------------------------------------------------- will.plugins.web
    ✓ HomePage

Verifying settings requested by plugins...
  ✓ PUBLIC_URL

Bootstrapping complete.

Starting core processes:
  ✓ Web server started.
  ✓ Scheduler started.
  ✓ Chat client started.
  ✓ Will is running.
</pre>

**Comment by KellyChan** [comment]
I have a bit confused about the tokens.

If I run `./run_will.py`, only the scope `view group` of the token is valid, others (such as `Administer Group`, `send message` etc) could not be verified.

If I tried the specific URL corresponding to the specific token with the command lines, they worked.

will/mixins/hipchat.py

<pre>
  8 ROOM_NOTIFICATION_URL = "https://%(server)s/v2/room/%(room_id)s/notification?auth_token=%(token)s    "
  9 ROOM_TOPIC_URL = "https://%(server)s/v2/room/%(room_id)s/topic?auth_token=%(token)s"
 10 PRIVATE_MESSAGE_URL = "https://%(server)s/v2/user/%(user_id)s/message?auth_token=%(token)s"
 11 SET_TOPIC_URL = "https://%(server)s/v2/room/%(room_id)s/topic?auth_token=%(token)s"
 12 USER_DETAILS_URL = "https://%(server)s/v2/user/%(user_id)s?auth_token=%(token)s"
 13 ALL_USERS_URL = "https://%(server)s/v2/user?auth_token=%(token)s&start-index=%(start_index)s"
</pre>

Tokens provided by hip chat

<pre>
V1 Token: (type) admin, (label) admin

V2 Tokens:
- Administer Group - Perform group administrative tasks. Note that this scope is restricted from updating the group owner's profile.
- Administer Room - Perform room administrative tasks
- Manage Rooms - Create, update, and remove rooms
- Send Message - Send private one-on-one messages
- Send Notification - Send room notifications
- View Group - View users, rooms, and other group information
- View Messages - View messages from chat rooms and private chats you have access to
- View Room - View room information and participants, but not history
</pre>

open a terminal on my local machine, typed the commands with the URLs (message/notification) with different tokens created at hipchat.com, they worked.

notification url with `Send Notification` token
<pre>
ROOM_NOTIFICATION_URL = "https://%(server)s/v2/room/%(room_id)s/notification?auth_token=%(token)s    "
</pre>

message url with `Send Message` token
<pre>
PRIVATE_MESSAGE_URL = "https://%(server)s/v2/user/%(user_id)s/message?auth_token=%(token)s"
</pre>

command line
<pre><code>
curl -d '{"color": "green", "message": "message", "notify": false, "messae_format": "text"}' -H 'Content-Type: application/json' https://api.hipchat.com/v2/room/room id/scope_name(message/notification)?auth_token=specific token
</code></pre>

**Comment by KellyChan** [comment]
Finally, I got it done on 1-to-1 chat at hipchat.com (but not valid at a chat room).

I found the problem that might be the API updated at hipchat.com for the V2 tokens.
Then I updated the will with the specific token, for example:

added V2_TOKEN_MESSAGE in config.py
<pre>
V2_TOKEN_MESSAGE="the token of `Send Message` scope"
</pre> 

updated the token in will/mixins/hipchat.py
<pre>
 27             # https://www.hipchat.com/docs/apiv2/method/private_message_user
 28             url = PRIVATE_MESSAGE_URL % {"server": settings.HIPCHAT_SERVER,
 29                                          "user_id": user_id,
 30                                          "token": settings.V2_TOKEN_MESSAGE}
</pre> 

ran `./run_will.py`, and went to hipchat, typed `hi` in 1-to-1 chat, it did!

**Comment by brandonsturgeon** [comment]
Hi @kwailamchan 

I know this is a very old issue, but did you still need any assistance with this?

**Comment by kwailamchan** [comment]
Hi @brandonsturgeon 

Thank you very much for your kind response, I think I had solved the problem at that time :-)

**Comment by skoczen** [comment]
Finally getting through the backlog, closing this one up as it looks fixed - @kwailamchan please reopen if that's wrong!

**Comment by Manasvibhatt297** [comment]
@brandonsturgeon I am facing the same problem..need ur assistance...please help.
`"Will is running"` is mentioned but no communication between hipchat and will

**Comment by Manasvibhatt297** [comment]
@kwailamchan how did u created 1-1 chat with will?

**Comment by skoczen** [comment]
@Manasvibhatt297 please track in the #263 you opened.  I'm leaving this issue closed.
