### ISSUE TITLE
reply with two answers

### ISSUE THREAD

**Issue by cliffxuan** [skoczen/will#191]
will always replies with two answers. i wonder if this is a config issue?

```
[15:00] cliff xuan: @will hello
[15:00] will: @cliff hi!
[15:00] will: @cliff hi!
```

**Comment by skoczen** [comment]
@cliffxuan thanks for reaching out!

Is it just the "hello" plugin, or other commands too?

**Comment by cliffxuan** [comment]
@skoczen it might be the just "hello" plugin.
guss it a feature not a bug :smile: ?

**Comment by cliffxuan** [comment]
i'm happy to close this issue. it doesn't bother me actually.

**Comment by skoczen** [comment]
@cliffxuan definitely not a feature! :)

Probably what's happening is that there are two "hello" plugins - one that's built into will, and one that's in your will install.

Can you check your plugins, and see if there's a "hello" hiding in there somewhere?

**Comment by brandonsturgeon** [comment]
Another option is that there's another Will process running somewhere in the background. Kill all run_will.py processes

**Comment by skoczen** [comment]
Possible, less likely.  He'd see duplicates on all commands, not just hello.  I have a similar double-hello on my personal will, but think it's kind of endearing so I've never fixed it.

**Comment by cliffxuan** [comment]
@skoczen yes, that's the case. there is a hiding "hello" plugin!
