### ISSUE TITLE
User joining hipchat causes will to stop responding to anything

### ISSUE THREAD

**Issue by shadow7412** [skoczen/will#192]
I'm getting an error fairly often which causes will to stop responding to all messages.

My current theory is that it happens when another user joins hipchat, but does not join any rooms that will is in.

```
ERROR    Error processing event handler: <bound method WillBot.join_rooms of <will.main.WillBot object at 0x7feeb0d30b90>>
Traceback (most recent call last):
  File "/home/panda/env/lib/python2.7/site-packages/sleekxmpp/xmlstream/xmlstream.py", line 1699, in _event_runner
    func(*args)
  File "/home/panda/env/lib/python2.7/site-packages/will/listener.py", line 67, in join_rooms
    self.update_will_roster_and_rooms()
  File "/home/panda/env/lib/python2.7/site-packages/will/listener.py", line 97, in update_will_roster_and_rooms
    user_data = self.full_hipchat_user_list[hipchat_id]
KeyError: u'****'
```

Where ***\* looks like the hipchat id (9 numbers)

Have you seen this before?

will==0.9.3
python==2.7.8

**Comment by skoczen** [comment]
Hey @shadow7412 , 

Haven't seen it before, but your theory is plausible -  though there are a number of other edge-case scenarios I could see causing it.   Can you wrap that code in a try/except, and test?

**Comment by camilian** [comment]
I get this error often.  Was there any troubleshooting done?

**Comment by shadow7412** [comment]
I didn't have much luck reproducing it consistently. Have you managed to worry or the cause?

**Comment by stevejarvis** [comment]
Our team is also crashing here regularly. I'll patch manually but hit this once every 2-3 days with 0.9.3.

**Comment by brandonsturgeon** [comment]
Has anyone here been able to reproduce this error so we can look into fixing it?

**Comment by skoczen** [comment]
Are folks still seeing this with > 0.9.4?  Any more info to help debug?

**Comment by shadow7412** [comment]
I've just updated to `will-0.9.4` (the latest on pip). Did you mean `>= 0.9.4` or is pip not up to date?

**Comment by skoczen** [comment]
`>=`,  - 1.0 is coming out shortly, which won't be much different.

**Comment by shadow7412** [comment]
I'll keep an eye out for it then.

**Comment by skoczen** [comment]
Fantastic, thanks!

**Comment by skoczen** [comment]
@shadow7412 @camilian @stevejarvis is this still an issue for you all?

Also, as a heads-up (especially with the HipChat->Stride migration) [Will 2 is out](https://heywill.io/will2), and there is [an upgrade guide](http://skoczen.github.io/will/upgrading_to_2/).

**Comment by shadow7412** [comment]
It hasn't happened for quite a while - so maybe it's gone away. Thanks for the guide - I'll get on that.

**Comment by skoczen** [comment]
@shadow7412 great to hear - I'll keep this open for a bit just in case, but close up if it seems sorted.

Great on 2.x as well - let me know if you hit any snags!

**Comment by shadow7412** [comment]
I decided to try the cheap and lazy upgrade path for a start, and migrating to the new options while it's running to minimise downtime.

I didn't get very far though;
` error in will setup command: 'install_requires' must be a string or list of strings containing valid 
project/version requirement specifiers`

Is this a problem with my virtualenv being python 2?

**Comment by wontonst** [comment]
If there are no further comments, I will close out this issue due to inactivity and HipChat deprecation.

**Comment by shadow7412** [comment]
Be my guest.
