### ISSUE TITLE
Add timestamp to log messages

### ISSUE THREAD

**Issue by ayashjorden** [skoczen/will#194]
Hi,
How can this be done?
Is it a Bottle config?

**Comment by skoczen** [comment]
Hey @ayashjorden 

Thanks for reaching out.  Can you give a bit more detail on what you're looking for?  Which log messages?  In what sort of output?

Thanks,
-Steven

**Comment by ayashjorden** [comment]
Hi,
I'm looking to add a DATETIME and log level to each message.
Actually my Will process is manages by Circus, I'm going to try and add the logging format there.

Thank you,
Yarden

**Comment by skoczen** [comment]
Got it - yeah, if you've got a higher level you can put it in, that's great.   Logging in will is a bit ad-hoc right now.  I'm open to that changing, and it becoming cohesive system that respects `logging` info, should you be interested in a PR!
