### ISSUE TITLE
Watson Dialog

### ISSUE THREAD

**Issue by tophsic** [skoczen/will#197]
Any plan to implement features interacting [IBM Watson Dialog](http://www.ibm.com/smarterplanet/us/en/ibmwatson/developercloud/dialog.html) :wink:?

**Comment by skoczen** [comment]
Not yet, but I love the idea!   How would you see it working?   Just a `@will watson ____`?   As a fallback to programmed responses?

**Comment by tophsic** [comment]
No idea for now :grimacing:. I just found Watson on working on [my first Will plugins](https://github.com/tophsic/anna)

And just discovering Python word, but it is not a valid excuse for your functionnal question :wink:

**Comment by brandonsturgeon** [comment]
I have my Will set up to have funny conversations with [CleverBot](http://www.cleverbot.com/) and the command is `@will -how are you doing?` with a hyphen in front

**Comment by brandonsturgeon** [comment]
Here's some documentation about where we could get started with this:

http://www.ibm.com/watson/developercloud/doc/getting_started/

And here's the watson python sdk: https://github.com/watson-developer-cloud/python-sdk

It certainly doesn't look like something we can just plug in, it would probably be a bit more involved. If we did end up going through the trouble to add it, we should probably make sure it's a bigger piece of Will with a fair amount of complexity.

**Comment by skoczen** [comment]
@tophsic @brandonsturgeon Broader comment here - yes, there are now plans to pull this kind of stuff in. :) I'll be opening up an issue to talk through the future of Will here shortly (prioritizing finally getting to the PRs, then reviewing the issues first), but short answer is yes to both integrations like Watson, Amazon AI, etc, as well as multiple communication backends (Slack, SMS, etc)

More soon!

**Comment by skoczen** [comment]
I'm going to close this for the moment, but yes, [it's coming](https://github.com/skoczen/will/issues/257). :)   PRs and help building are very much welcome!
