### ISSUE TITLE
BDD tests

### ISSUE THREAD

**Issue by tophsic** [skoczen/will#200]
Do you think it can be possible to implement [Behave](http://pythonhosted.org/behave/) (or other framework) tests.

Just ask because I do not know well Python and Will architecture yet.

I will have a look.

**Comment by tophsic** [comment]
Hi, here is what I've done for ecolutis/anna#3. If you can have a look, thx!

**Comment by brandonsturgeon** [comment]
Hi @tophsic ,

BDD is a great way to develop, I was able to do a littel bit of behavior driven development on a couple of circumstances, and I appreciated the structure it provided.

I imagine that this is probably something that would affect @skoczen or whatever the primary maintainer may be the most, so it's probably going to be left to them.

Your link to `ecolutis/anna` is a dead link now, so I'm afraid we can't see what's been done anymore (Understandable, seeing as how long ago this was posted)

Did you want to leave this issue open to leave conversation open about this, or would you feel comfortable closing it?

**Comment by tophsic** [comment]
Hi,

You can surely close this issue open. I do not use Will anymore and the company where I wrote Anna closed the repo.

Regards

**Comment by skoczen** [comment]
@tophsic bummer!  I'd love to get BDD in will for a future release!  If you have any thoughts you'd like to share on how anna was set up, please reopen this and share - I'd love to learn from your experience on what worked and didn't, and hear any suggestions you have!
