### ISSUE TITLE
Remove hello.py from generate_will_project

### ISSUE THREAD

**Issue by derek-adair** [skoczen/will#202]
Pretty nit-picky but i spent a large amount of time trying to debug why will was saying hi twice.  Perhaps a different example would prevent dismay for noobies like myself?

**Comment by skoczen** [comment]
+1 !  Actually, I'd rather have it either removed from core will, or a similar, simple but friendly method added in generate.  PR welcome! 

Thanks for your continued work on this!

**Comment by tophsic** [comment]
:+1:

**Comment by shadow7412** [comment]
Now that you mention it, I did the same thing :stuck_out_tongue:
Though having hello.py in core will I think adds the the 'friendliness' of the bot... I'd sooner see the example changed personally. Either or though.

**Comment by brandonsturgeon** [comment]
Where's the duplicated hello script? It seems like the current example is now `bonjour` instead of `hello`/`hi`

**Comment by derek-adair** [comment]
Its been a while since i've looked at this project/issue but i believe its a simple bug caused how the [generate_will_project.py ](https://github.com/skoczen/will/blob/master/will/scripts/generate_will_project.py#L53) script works

**Comment by skoczen** [comment]
Changed the example to 'Good Morning' - thanks @derek-adair @brandonsturgeon !

**Comment by derek-adair** [comment]
@skoczen makes a fabled appearance!!!! ;)
