### ISSUE TITLE
Recursive reminder

### ISSUE THREAD

**Issue by tophsic** [skoczen/will#203]
Is that possible to add a recursive reminder?

```
@will remind @all to stand up for tech meeting on each tuesday at 10:30
```

**Comment by skoczen** [comment]
Hey @tophsic ,

Nope - the way to do that is to use the [`@periodic`](http://skoczen.github.io/will/plugins/notice/#take-an-action-on-a-schedule) method. 

We do just that for our standup!

**Comment by tophsic** [comment]
Thx
