### ISSUE TITLE
Google image API deprecated

### ISSUE THREAD

**Issue by tophsic** [skoczen/will#205]
The Google API Will use for `image me` action is no longer available.

Here is the 200 response to http://ajax.googleapis.com/ajax/services/search/images?q=sleepy&v=1.0&safe=active&rsz=8.

``` json
{"responseData": null, "responseDetails": "This API is no longer available.", "responseStatus": 403}
```

**Comment by shadow7412** [comment]
I've had a quick look - and it doesn't look like there is going to be a way to do this that doesn't involve a google api key.

**Comment by antgel** [comment]
What's the sanest way forward? Many users (us included) do have API credentials, which I guess we could put in Will envvars. Will the code need a big refactor?

**Comment by skoczen** [comment]
Probably not a big refactor.  Shortest path forward is probably for someone to figure it out, update the plugin and docs, and submit a PR.  Alternate approaches could be a different API (flickr, etc).

I'm open to anything - may have some time to work on this and other will stuff next week!

**Comment by antgel** [comment]
That would be cool. :)

**Comment by shadow7412** [comment]
Please give https://github.com/skoczen/will/pull/211 a whirl.

**Comment by skoczen** [comment]
Closing, as it's merged!  Thanks, @shadow7412 !
