### ISSUE TITLE
Why does will run non-daemonic threads vs. daemonic?

### ISSUE THREAD

**Issue by pepedocs** [skoczen/will#212]
Hi, 

I've read a bit about how will bootstraps its threads and the first thing I've noticed (correct me if I'm wrong) is that it is running non-daemonic threads.  Is there a reason for using non-daemonic threads over daemonic ones?  

```
https://github.com/skoczen/will/blob/d074cb2b577264f0ab23215b3dd5cab590551abb/will/main.py#L111
```

I'm chasing a possible memory leak issue when will is run for a couple of days and I'm interested on how will cleans up itself after being killed abruptly (e.g. by an oom killer).

Cheers

**Comment by brandonsturgeon** [comment]
I've noticed that after killing the main run_will.py instance, he'll still sometimes run. This makes it hard to make a script to auto restart will. I don't know any specifics, but I was curious.

**Comment by pepedocs** [comment]
This is a late post, but I still would like to share some updates;

So the cause of the memory leak I was chasing last january was in hireds library and python's ssl lib. This was only evident on a particular python version. Ping me when you're interested about the details.

@brandonsturgeon You may need to send a SIGINT to will so that it can exit cleanly, same as pressing Ctrl+C or a python KeyboardInterrupt.

Cheers

**Comment by brandonsturgeon** [comment]
@pepedocs I did actually end up sending SIGINT signal to will and it solved my problem of extra threads still running.

Can this issue be closed, or is there still more to talk about?

**Comment by pepedocs** [comment]
@brandonsturgeon Yes you may close it.

**Comment by skoczen** [comment]
@pepedocs closing this up as requested, but just to answer your question - non-daemonic was to prevent loose threads from running in the background when a SIGINT was passed.  When I was running daemonic and a plugin blew up, etc, results were *very* inconsistent and will could be running in the background with no proper way to kill it.

Open to other approaches if you have a better one!
