### ISSUE TITLE
Logging?

### ISSUE THREAD

**Issue by brandonsturgeon** [skoczen/will#213]
Is there an easy way to implement or use the logging system Will uses without having to import and configure python's base logging system into every plugin we make?

**Comment by skoczen** [comment]
Nope.  But there should be. :)

**Comment by skoczen** [comment]
Just a note - in Will 2 (#258), this works with

`import logger`.

:)

**Comment by skoczen** [comment]
Closing this up, as Will 2 just uses the builtin python logger, and configures it by default!
