### ISSUE TITLE
ConnectionError

### ISSUE THREAD

**Issue by phanig** [skoczen/will#217]
Hi All,

I'm new to Will and ran into below error, Please help figure it out :

Verifying environment...
  ✓ WILL_USERNAME
  ✓ WILL_PASSWORD
  ✓ WILL_V2_TOKEN
  ✓ WILL_REDIS_URL

Verifying credentials...
  ✓ Big Brother authenticated
  ✓ @BigBrother verified as handle

Loading configuration...
  Importing config.py... 
    ✓ Valid.
  Verifying settings... 
    ! Warning: no ROOMS list found in the environment or config.  This is ok - Will will just join all available rooms.
    ! Warning: no HTTPSERVER_PORT found in the environment or config.  Defaulting to ':80'.
    - Note: WILL_REDIS_URL not set.  Defaulting to redis://localhost:6379/7.
    - Note: REDIS_MAX_CONNECTIONS not set. Defaulting to 4.
    ! Warning: no PUBLIC_URL found in the environment or config.  Defaulting to 'http://localhost:80'.
    ✓ ALLOW_INSECURE_HIPCHAT_SERVER
    ✓ ADMINS
    ✓ HANDLE
    ✓ HTTPSERVER_PORT
    ✓ HIPCHAT_SERVER
    ✓ NAME
    ✓ PUBLIC_URL
    ✓ PLUGINS
    ✓ PLUGIN_BLACKLIST
    ✓ PASSWORD
    ✓ ROOMS
    ✓ REDIS_URL
    ✓ REDIS_MAX_CONNECTIONS
    ✓ REQUESTS_OPTIONS
    ✓ STORAGE_BACKEND
    ✓ TEMPLATE_DIRS_PICKLED
    ✓ USERNAME
    ✓ USE_PROXY
    ✓ V1_TOKEN
    ✓ V2_TOKEN

Verifying rooms...
  ✓ Joining all 300 known rooms.

Bootstrapping storage...
  ✓ Bootstrapped!

Bootstrapping plugins...
  
  Administrative actions ------------------------------------------------ will.plugins.admin
    ✓ Ping
    ✓ Version
    ✓ Storage
    ✓ Say
    ✓ KeepAlive
  
  Hipchat actions --------------------------------------------------- will.plugins.chat_room
    ✓ NewTopic
    ✓ Rooms
    ✓ Roster
  
  Devops, server stuff, and uptime ------------------------------------- will.plugins.devops
    ✓ GithubIsUp
    ✓ BitBucketIsUp
    ✗ PagerDuty (blacklisted)
    ✓ HerokuIsUp
    ✓ EmergencyContacts
    ✓ HipChatIsUp
  
  Old-fashioned friendliness ----------------------------------------- will.plugins.friendly
    ✓ Thanks
    ✓ Snickerdoodles
    ✓ RandomTopic
    ✓ TalkBack
    ✓ ItsLove
    ✓ Hello
    ✓ MorninEvenin
  
  It can't all be about work! --------------------------------------------- will.plugins.fun
    ✓ GooglePoem
    ✓ Pug
    ✓ Definition
  
  Help ------------------------------------------------------------------- will.plugins.help
    ✓ ProgrammerHelp
    ✓ Help
  
  Plugins -------------------------------------------------------------------------- plugins
    ✓ Hello
  
  Productivity --------------------------------------------------- will.plugins.productivity
    ✓ Remind
    ✗ Time (blacklisted)
    ✗ Hangout (blacklisted)
    ✗ Bitly (blacklisted)
    ✓ Images
  
  Web pages --------------------------------------------------------------- will.plugins.web
    ✓ HomePage

Verifying settings requested by plugins...
  ✓ PUBLIC_URL
  
Bootstrapping complete.

Starting core processes:
  ✓ Web server started.
  ✓ Scheduler started.
Exception in thread Thread-5:
Traceback (most recent call last):
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/Users/gullaph/projects/virtualenv_hipchat/lib/python2.7/site-packages/will/decorators.py", line 27, in wrapped_f
    f(*args, **kwargs)
  File "/Users/gullaph/projects/virtualenv_hipchat/lib/python2.7/site-packages/will/decorators.py", line 104, in wrapped_f
    f(*args, **kwargs)
  File "/Users/gullaph/projects/virtualenv_hipchat/lib/python2.7/site-packages/will/plugins/admin/keep_alive.py", line 14, in ping_keep_alive
    requests.get("%s%s" % (settings.PUBLIC_URL, keep_alive_url))
  File "/Users/gullaph/projects/virtualenv_hipchat/lib/python2.7/site-packages/requests/api.py", line 59, in get
    return request('get', url, **kwargs)
  File "/Users/gullaph/projects/virtualenv_hipchat/lib/python2.7/site-packages/requests/api.py", line 48, in request
    return session.request(method=method, url=url, **kwargs)
  File "/Users/gullaph/projects/virtualenv_hipchat/lib/python2.7/site-packages/requests/sessions.py", line 451, in request
    resp = self.send(prep, **send_kwargs)
  File "/Users/gullaph/projects/virtualenv_hipchat/lib/python2.7/site-packages/requests/sessions.py", line 557, in send
    r = adapter.send(request, **kwargs)
  File "/Users/gullaph/projects/virtualenv_hipchat/lib/python2.7/site-packages/requests/adapters.py", line 407, in send
    raise ConnectionError(err, request=request)
ConnectionError: ('Connection aborted.', error(60, 'Operation timed out'))

**Comment by mushtaqak** [comment]
I am getting the same traceback.

**Comment by phanig** [comment]
Guys, any help is much appreciated. Thanks

**Comment by ShawnMilo** [comment]
The traceback shows a timeout connecting to a server. What are the values of `settings.PUBLIC_URL` and `keep_alive_url` in scope in `keep_alive.py`?

**Comment by phanig** [comment]
Closing this issue as this error seems to be related to my firewall.

**Comment by mushtaqak** [comment]
@phanig Can you explain. What did you do to make this working ?
