### ISSUE TITLE
Can't include "/code" "/quote" in messages anymore?

### ISSUE THREAD

**Issue by brandonsturgeon** [skoczen/will#220]
There was a hipchat update recently (A big-ish one) and after that update whenever I include "/code" or "/quote" (or anything like that) in a message for Will to send, it just sends it escaped so it doesn't actually format/color it like Code or like a Quote.

Example:
![screen shot 2016-03-29 at 10 42 34 am](https://cloud.githubusercontent.com/assets/7936439/14114100/60f0e73a-f59b-11e5-9666-0b71d40d6b72.png)

This may not be something we can fix, in that case maybe we bring it up with Hipchat? I know we've done that as a project before and they were very receptive.

**Comment by skoczen** [comment]
Yikes.   Are you sending I assume you're sending that message with `html=False`?

**Comment by brandonsturgeon** [comment]
I didn't specify the html arg. Doesn't seem to make a difference though :/

![screen shot 2016-03-31 at 12 36 13 pm](https://cloud.githubusercontent.com/assets/7936439/14184944/4a1be2c8-f73d-11e5-86a0-096cdc71f639.png)

**Comment by skoczen** [comment]
Damn.   Yep, let's bring it up with them.  They've been mixed in terms of responsiveness - hope that this time is a good one!

**Comment by brandonsturgeon** [comment]
I put in a ticket and the guy was very nice and thorough. He said it's already a known issue.

https://jira.atlassian.com/browse/HCPUB-201 

Be sure to vote for that issue and watch it too, that'll put it higher up on the to-do list.

**Comment by brandonsturgeon** [comment]
Also, Hipchat has been sucking more and more lately. Shoutout to #150

**Comment by brandonsturgeon** [comment]
> Fixed: Text-based API messages that begin with /code or /quote should now render properly in chat according to the slash command

Boom, latest update (4.0.8)

**Comment by brandonsturgeon** [comment]
Not going to re-open this issue because it's irrelevant to this project, but just wanted to let you guys know that this doesn't actually seem to be fixed in the latest update. I've bumped the issue tracker on Hipchat.

**Comment by brandonsturgeon** [comment]
Yeah, looks like they mistakenly included the fix in the changelog before it was actually done

**Comment by brandonsturgeon** [comment]
https://jira.atlassian.com/browse/HCPUB-201

4.0.9 actually fixes this problem, seems like it's all good to go.
