### ISSUE TITLE
Will sends responses to one room only, regardless of room where will heard 

### ISSUE THREAD

**Issue by mensoh** [skoczen/will#227]
Hi, 
I just wrote my first plugin, an alternative version of the 'what time is it' plugin that uses Google API's and circumvents the necessity of using the other API stuff. 

I use the @hear command and when I type 'what time is it in X' the response always goes to the same room, not necessarily the room will heard me ask it in. I'm sure I'm doing something wrong. Any pointers would be highly appreciated

**Comment by mensoh** [comment]
fixed sorry, forgot message=message at the end, nvm :)

**Comment by skoczen** [comment]
All good - glad it's working!
