### ISSUE TITLE
ERROR    Could not match certficate against hostname: <hostname>

### ISSUE THREAD

**Issue by mensoh** [skoczen/will#228]
Hi, 
When running will to connect to our self-hosted server will doesn't seem to like my SSL certificate (from letsencrypt).. It just keeps saying: 

```
ERROR    Could not match certficate against hostname: ourhost.org
ERROR    Socket Error #9: Bad file descriptor
ERROR    Could not match certficate against hostname: ourhost.org
ERROR    Socket Error #9: Bad file descriptor
```

and so on, and so on... 
I'm not sure what the problem is or where the connection is being made to the server in the code. The SSL cert is fine and accepted by pretty much everything (except our JIRA and Confluence keystores where I had to add it manually).

I've appended the cert from the server to /etc/ssl/certs/ca-certificates.crt but that didn't help either. The host is specified in the cert too, so I'm not sure what's going on. Any help would be appreciated, I don't really want to run will with ALLOW_INSECURE_HIPCHAT_SERVER = True but it's the only way atm unfortunately...

**Comment by mensoh** [comment]
Any advice or tips on this would be greatly appreciated...

**Comment by pepedocs** [comment]
@mensoh It looks like its failing in sleekxmpp code, you may wanna look at https://github.com/fritzy/SleekXMPP/blob/sleek-1.3.1/sleekxmpp/xmlstream/cert.py#L183 

, and run through on your certificate and compare it with the one's being checked in the code.

**Comment by brandonsturgeon** [comment]
@mensoh 

Hi there! 

Sorry you haven't gotten a response yet, it seems like everyone over here is very busy in their day-to-day lives.

Could you still use some help with this?

**Comment by skoczen** [comment]
Closing this up as it's been almost a year without an affirmative still-happening reply - please reopen if this is still an issue!
