### ISSUE TITLE
how to filter debug logs??

### ISSUE THREAD

**Issue by cachrisman** [skoczen/will#231]
I'm trying to get more information about what is causing a `Socket Error #104` and I set `LOGLEVEL = "DEBUG"` in `config.py` and I'm getting a ton of errors like this:

```
D2: <dict object at 0x7fa2be0cc398>
INFO     D2: <dict object at 0x7fa2be0cc398>
T4: <type 'datetime.datetime'>
INFO     T4: <type 'datetime.datetime'>
```

I'm sure it has some purpose, but to me it seems like useless chaff, so I'd like to filter it out of the logs. This is my run_will.py file:

```
#!/usr/bin/env python
from will.main import WillBot
import logging

logger = logging.getLogger()

class FilterLogs(logging.Filter):
    def filter(self, record):
        return not ((record.getMessage().find("D2: <dict object at") != -1) or (record.getMessage().find("type 'datetime.datetime'") != -1))

logger.addFilter(FilterLogs())

if __name__ == '__main__':
    bot = WillBot()
    bot.bootstrap()
```

but it doesn't seem to be working. This is my first attempt at filtering the logging, so its probably a simple mistake on my part. 

How do I filter the log output that Will Bot produces?

**Comment by brandonsturgeon** [comment]
You may want to look into filtering the output at the shell level. Grep is a very powerful tool that should be able to accomplish everything you want here, without the need to edit Will's source code.

**Comment by skoczen** [comment]
Both should be possible - you should definitely be able to change the logging level and filter.  My guess is that either this is coming from the threading/import space, or there's a tweak needed with the filter.

@cachrisman did you get this resolved?

**Comment by skoczen** [comment]
@cachrisman closing this up, as I'm cleaning out issues getting ready for 2.1, please reopen if you're still having this issue!
