### ISSUE TITLE
Run chatbot with self hosted hipchat

### ISSUE THREAD

**Issue by perzizzle** [skoczen/will#238]
Has anyone run Will on a self hosted instance of hipchat? I've configured HIPCHAT_SERVER to point to our self hosted instance but when I executer ./run_will.py I get stuck in the loop below.

I've tried grepping for "chat.btf", "hipchat.com" etc but I can't figure out where its getting that url and why.
`
...
✓ Scheduler started.
DEBUG    Loaded Plugin: RFC 6121: Stream Feature: Subscription Pre-Approval
DEBUG    Loaded Plugin: RFC 6120: Stream Feature: SASL
DEBUG    Loaded Plugin: XEP-0030: Service Discovery
DEBUG    Loaded Plugin: XEP-0004: Data Forms
DEBUG    Loaded Plugin: XEP-0045: Multi-User Chat
DEBUG    DNS: Querying SRV records for chat.btf.hipchat.com
DEBUG    DNS: No SRV records for chat.btf.hipchat.com.
DEBUG    DNS: Querying chat.btf.hipchat.com for AAAA records.
DEBUG    DNS: No AAAA records for chat.btf.hipchat.com
DEBUG    DNS: Querying chat.btf.hipchat.com for A records.
DEBUG    Connecting to 54.85.107.163:5222
DEBUG    Event triggered: socket_error
ERROR    Could not connect to 54.85.107.163:5222. Socket Error #111: Connection refused
DEBUG    Connecting to 54.87.186.244:5222
`

**Comment by dearchap** [comment]
Did you set the WILL_HIPCHAT_SERVER env variable to the address of your local hipchat server ?

**Comment by CloudSurgeon** [comment]
I had this same issue. I had set HIPCHAT_SERVER in the config.py, so I thought that was enough. I removed that entry from config.py and added WILL_HIPCHAT_SERVER to my environment variables, now I am up and running.

**Comment by brandonsturgeon** [comment]
@perzizzle Hi there. Were you able to get Will running on your self-hosted server?

**Comment by dearchap** [comment]
Yes I had to move my Will install onto another host and it just worked !!!

**Comment by edenzik** [comment]
I also ran into this issue. Thanks for the help, WILL_HIPCHAT_SERVER indeed fixed it. It should probably be clearer in the docs...

**Comment by skoczen** [comment]
Sounds like @edenzik @CloudSurgeon @dearchap and @perzizzle were all able to get their wills running, so closing this up - PRs for improved docs for self-hosted would be happily accepted! (I'm not running on self-hosted, so am pretty far from domain knowledge.)
