### ISSUE TITLE
Will is responding duplicated

### ISSUE THREAD

**Issue by demian711** [skoczen/will#240]
```
  ___/-\___
```

  **_|______**_|___
     |         |
     |--O---O--|
     |         |
     |         |
     |  _**/  |
     |_______**|

```
  Will: Hi!
```

Verifying environment...
  ✓ WILL_USERNAME
  ✓ WILL_PASSWORD
  ✓ WILL_V2_TOKEN
  ✓ WILL_REDIS_URL

Verifying credentials...
  ✓ Demian Bot authenticated
  ✓ @DemianBot verified as handle

Loading configuration...
  Importing config.py...
    ✓ Valid.
  Verifying settings...
    ! Warning: no ROOMS list found in the environment or config.  This is ok - Will will just join all available rooms.
    ! Warning: no HTTPSERVER_PORT found in the environment or config.  Defaulting to ':80'.
    - Note: REDIS_MAX_CONNECTIONS not set. Defaulting to 4.
    ! Warning: no PUBLIC_URL found in the environment or config.  Defaulting to 'http://localhost:80'.
    ! Warning: no V1_TOKEN found in the environment or config.This is generally ok, but if you have more than 30 rooms, you may recieve rate-limit errors without one.
    ✓ ALLOW_INSECURE_HIPCHAT_SERVER
    ✓ ADMINS
    ✓ HANDLE
    ✓ HTTPSERVER_PORT
    ✓ HIPCHAT_SERVER
    ✓ NAME
    ✓ PUBLIC_URL
    ✓ PLUGINS
    ✓ PLUGIN_BLACKLIST
    ✓ PASSWORD
    ✓ REDIS_URL
    ✓ REDIS_MAX_CONNECTIONS
    ✓ ROOMS
    ✓ REQUESTS_OPTIONS
    ✓ STORAGE_BACKEND
    ✓ TEMPLATE_DIRS_PICKLED
    ✓ USERNAME
    ✓ USE_PROXY
    ✓ V2_TOKEN

Verifying rooms...
  ✓ Joining all 2 known rooms.

Bootstrapping storage...
  ✓ Bootstrapped!

Bootstrapping plugins...

  Administrative actions ------------------------------------------------ will.plugins.admin
    ✓ Say
    ✓ Version
    ✓ Storage
    ✓ KeepAlive
    ✓ Ping

  Hipchat actions --------------------------------------------------- will.plugins.chat_room
    ✓ Roster
    ✓ Rooms
    ✓ NewTopic

  Devops, server stuff, and uptime ------------------------------------- will.plugins.devops
    ✓ HerokuIsUp
    ✗ PagerDuty (blacklisted)
    ✓ GithubIsUp
    ✓ EmergencyContacts
    ✓ HipChatIsUp
    ✓ BitBucketIsUp

  Old-fashioned friendliness ----------------------------------------- will.plugins.friendly
    ✓ Hello
    ✓ ItsLove
    ✓ Thanks
    ✓ TalkBack
    ✓ MorninEvenin
    ✓ Snickerdoodles
    ✓ RandomTopic

  It can't all be about work! --------------------------------------------- will.plugins.fun
    ✓ GooglePoem
    ✓ Definition
    ✓ Pug

  Help ------------------------------------------------------------------- will.plugins.help
    ✓ ProgrammerHelp
    ✓ Help

  Plugins -------------------------------------------------------------------------- plugins
    ✓ Hello

  Productivity --------------------------------------------------- will.plugins.productivity
    ✓ Remind
    ✗ Bitly (blacklisted)
    ✗ Time (blacklisted)
    ✗ Hangout (blacklisted)
    ✓ Images

  Web pages --------------------------------------------------------------- will.plugins.web
    ✓ HomePage

Verifying settings requested by plugins...
  ✓ PUBLIC_URL

Bootstrapping complete.

Starting core processes:
  ✓ Web server started.
  ✓ Scheduler started.
  ✓ Chat client started.
  ✓ Will is running.

All seems to work perfect. But if I do @will hi. it replays hello! hello! . Separate lines. Like if it receives two commands

**Comment by brandonsturgeon** [comment]
Try removing the 'hello' plugin from `will/plugins/friendly/hello.py` and restart your Will.

**Comment by brandonsturgeon** [comment]
@demian711 Did that help? :)

**Comment by skoczen** [comment]
Closing this, because @brandonsturgeon nailed the problem, and it's also been fixed from 0.9.4 on with a better generate script!

Please reopen if that's not right!
