### ISSUE TITLE
ERROR    Error reading from XML stream.

### ISSUE THREAD

**Issue by dearchap** [skoczen/will#241]
```
  ___/-\___
```

  **_|______**_|___
     |         |
     |--O---O--|
     |         |
     |         |
     |  _**/  |
     |_______**|

```
  Will: Hi!
```

Verifying environment...
  ✓ WILL_USERNAME
  ✓ WILL_PASSWORD
  ✓ WILL_V2_TOKEN
  ✓ WILL_REDIS_URL

Verifying credentials...
  ✓ bay max authenticated
  ✓ @baymax verified as handle

Loading configuration...
  Importing config.py... 
    ✓ Valid.
  Verifying settings... 
    ! Warning: no DEFAULT_ROOM found in the environment or config.  Defaulting to 'baymaxtest', the first one.
    - Note: WILL_REDIS_URL not set.  Defaulting to redis://localhost:6379/7.
    - Note: REDIS_MAX_CONNECTIONS not set. Defaulting to 4.
    ! Warning: no V1_TOKEN found in the environment or config.This is generally ok, but if you have more than 30 rooms, you may recieve rate-limit errors without one.
    ✓ ALLOW_INSECURE_HIPCHAT_SERVER
    ✓ ADMINS
    ✓ DEFAULT_ROOM
    ✓ HANDLE
    ✓ HTTPSERVER_PORT
    ✓ HIPCHAT_SERVER
    ✓ NAME
    ✓ PUBLIC_URL
    ✓ PLUGIN_BLACKLIST
    ✓ PASSWORD
    ✓ PLUGINS
    ✓ REDIS_URL
    ✓ REDIS_MAX_CONNECTIONS
    ✓ ROOMS
    ✓ REQUESTS_OPTIONS
    ✓ STORAGE_BACKEND
    ✓ TEMPLATE_DIRS_PICKLED
    ✓ USERNAME
    ✓ USE_PROXY
    ✓ V2_TOKEN

Verifying rooms...
  ✓ Joining the 1 room specified.

Bootstrapping storage...
  ✓ Bootstrapped!

Bootstrapping plugins...

  Administrative actions ------------------------------------------------ will.plugins.admin
    ✓ Ping
    ✓ KeepAlive
    ✓ Say
    ✓ Storage
    ✓ Version

  Hipchat actions --------------------------------------------------- will.plugins.chat_room
    ✓ NewTopic
    ✓ Rooms
    ✓ Roster

  Devops, server stuff, and uptime ------------------------------------- will.plugins.devops
    ✓ BitBucketIsUp
    ✓ GithubIsUp
    ✓ EmergencyContacts
    ✗ PagerDuty (blacklisted)
    ✓ HipChatIsUp
    ✓ HerokuIsUp

  Old-fashioned friendliness ----------------------------------------- will.plugins.friendly
    ✓ TalkBack
    ✓ Snickerdoodles
    ✓ Hello
    ✓ MorninEvenin
    ✓ Thanks
    ✓ RandomTopic
    ✓ ItsLove

  It can't all be about work! --------------------------------------------- will.plugins.fun
    ✓ GooglePoem
    ✓ Definition
    ✓ Pug

  Help ------------------------------------------------------------------- will.plugins.help
    ✓ ProgrammerHelp
    ✓ Help

  Plugins -------------------------------------------------------------------------- plugins
    ✓ Hello

  Productivity --------------------------------------------------- will.plugins.productivity
    ✓ Remind
    ✗ Hangout (blacklisted)
    ✓ Images
    ✗ Time (blacklisted)
    ✗ Bitly (blacklisted)

  Web pages --------------------------------------------------------------- will.plugins.web
    ✓ HomePage

Verifying settings requested by plugins...
  ✓ PUBLIC_URL

Bootstrapping complete.

Starting core processes:
  ✓ Web server started.
  ✓ Scheduler started.
  ✓ Chat client started.
  ✓ Will is running.
ERROR    Error reading from XML stream.
ERROR    Error reading from XML stream.

The bot is not showing up as active in hipchat and in any rooms. 

I have the following environment variables defined

WILL_HIPCHAT_SERVER=XXX
WILL_HTTPSERVER_PORT=8080
WILL_PASSWORD=XXX
WILL_PUBLIC_URL=http://[my-server-ip]
WILL_ROOMS=baymaxtest
WILL_USERNAME=YY@[local-hipchat-server-name]
WILL_V2_TOKEN=XXXX

I can do the following 
# curl http://localhost:8080/say/Oh%20dear

and have the message show up in default chat room. 

Am I missing some configuration ?

**Comment by woohgit** [comment]
👍

**Comment by Binaym** [comment]
Seeing similar issue 

Starting core processes:
  âœ“ Web server started.
  âœ“ Scheduler started.
  âœ“ Chat client started.
  âœ“ Will is running.
ERROR    Error reading from XML stream.
ERROR    Error reading from XML stream.
ERROR    Error reading from XML stream.

**Comment by brandonsturgeon** [comment]
Hi there!

Sorry that you haven't received a reply yet, it seems like everyone over here is really busy in their lives right now.

Have you solved this yourself?

A lot of times when people receive this error, it's something to do with network auth. Usually certificates or something. Some people have done a variety of things to temporarily get around this specific problem, one of the most recent ones was to uncomment `ALLOW_INSECURE_HIPCHAT_SERVER` in the config. But it looks like you've already done that.

@dearchap  @Binaym If you're still struggling with this or would like to find a solution, I'd be happy to take a look at the full trace to help you figure out what's causing your issue(s).

**Comment by skoczen** [comment]
Closing this as it seems stale, and there wasn't a response to @brandonsturgeon - please reopen if you're still having trouble!
