### ISSUE TITLE
Message object documentation

### ISSUE THREAD

**Issue by ayashjorden** [skoczen/will#242]
Hi,
This may seem obvious, but where can I find the Message object docs?

Tried to look at the code but didn't find anything :(

Thank you,
Yarden

**Comment by brandonsturgeon** [comment]
It looks like the Message object is just a dictionary.  What kinds of things are you looking for? I remember when I was playing around with extracting info from the message object, I dug into hipchat's api documentation, and poked around in Will's internals.

I don't think there's any documentation, but if you're looking for something specific maybe I can lend a hand?

**Comment by ayashjorden** [comment]
If its just the response that HipChat api returns, maybe it worth mentioning that with a link.

I was looking for what other methods/keys does the Message object has? I mainly use the `message.sender.nick` but if I would have the additional info, it would help me understand what directions I can think about :)

**Comment by brandonsturgeon** [comment]
Have you tried making a quick `respond_to` and printing the message arg? I think it's just a dictionary, so you should be able to [print](https://docs.python.org/2/library/pprint.html) it and explore. 

I don't have a running will instance to play around with, and I haven't for awhile, so excuse me if I'm a bit rusty.

**Comment by brandonsturgeon** [comment]
https://www.hipchat.com/docs/apiv2/ Here's the apiv2 documentation, but they don't outline what a Message response looks like

**Comment by ayashjorden** [comment]
Thank you for the link.
I'll just have to inspect it to get what I need.
