### ISSUE TITLE
Rooms fetched with V1 ID aren't room objects

### ISSUE THREAD

**Issue by PaulMcMillan** [skoczen/will#243]
The code here:
https://github.com/skoczen/will/blob/master/will/mixins/room.py#L61

Fails to do a `Room(**room)` like the code here does:
https://github.com/skoczen/will/blob/master/will/mixins/room.py#L78

This means rooms fetched with a V1 api key aren't "room" objects and so they don't have history property.

**Comment by PaulMcMillan** [comment]
It also apparently needs `room['id'] = room['room_id']` to match up the old and new datastructures

**Comment by brandonsturgeon** [comment]
This is a good find!
Are you interested in making a pull request?

**Comment by PaulMcMillan** [comment]
I wish I could. Unfortunately, I can't without a bunch of paperwork from my employer :/

**Comment by brandonsturgeon** [comment]
Huh, I'm very curious about why that is, haha. 

I'm not able to either, because I don't have any current instance of Will, so this might be up to @skoczen :/

**Comment by skoczen** [comment]
I'm closing this because there was a PR that (to my understanding of this issue) fixed and merged this into 0.9.4.  Please reopen if that's wrong!
