### ISSUE TITLE
ask user for response

### ISSUE THREAD

**Issue by chutes** [skoczen/will#250]
When a user sends a message to will, have will ask the user if they're sure that's the message they want sent

**Comment by brandonsturgeon** [comment]
This wouldn't be a good feature to have on every single Will request. However, you can create a plugin that checks for confirmation on specific commands!

**Comment by chutes** [comment]
how would you suggest handling this?
Right now I have something as shown below.  This would require me to implement it specifically for each command I want confirmation on though...

`class DeployPackage(WillPlugin):

    deploy_package_requests = {}

    @respond_to("(?P<command>deploy package .*)")
    def deploy_package(self, message, command):
        self.deploy_package_requests[message.sender['hipchat_id']] = command

        self.reply(message, 'are you sure?')

    @respond_to("^yes$")
    def yes(self, message):
        if message.sender['hipchat_id'] in self.deploy_package_requests:
            command = self.deploy_package_requests[message.sender['hipchat_id']]

            parsed_command = Job.parse_command(
                command=command,
                user_id=message.sender['hipchat_id'],
                room_id=message.room['name'],
            )

            self.reply(message, 'deploying package {} {} to {}!'.format(
                parsed_command['product'],
                parsed_command['branch'],
                parsed_command['environment']
            ))

            del self.deploy_package_requests[message.sender['hipchat_id']]

        else:
            self.reply(message, "I don't know what you're trying to confirm")

    @respond_to("^no$")
    def no(self, message):
        if message.sender['hipchat_id'] in self.deploy_package_requests:
            self.reply(message, 'removing request: {}'.format(
                self.deploy_package_requests[message.sender['hipchat_id']]))

            del self.deploy_package_requests[message.sender['hipchat_id']]`

**Comment by brandonsturgeon** [comment]
You would want to modularize the response handling so that it can be used from any function.

`job_utils.py`
```
@respond_to("^SERIOUSLY clear all waiting jobs$")
def clear_waiting_jobs(self, message):
    jobs = self.load("awaiting_confirmation", [])
    self.save("awaiting_confirmation", [])

    self.reply("Cleared {} job(s)!".format(len(jobs)))

def save_command(job_type, callback, message):
    job = { "job_type": job_type, "caller": message.sender["hipchat_id"], "callback": callback }
    
    jobs = self.load("awaiting_confirmation", [])
    jobs.append(job )

    self.save("awaiting_confirmation", job )

    self.ask_for_confirmation(message)

def ask_for_confirmation(self, message)
    self.reply(message, "Are you sure? (reply yes or no)")

@respond_to("^yes$")
def yes(self, message):
    # check redis store for commands which needs confirmation
    # if there is a pending command which needs confirmation, make sure that the person confirming is also the person who issued the command. Then run the callback and remove command from redis store
    # otherwise; either ignore the message or reply with "no jobs need confirmation!"

@respond_to("^no$")
def no(self, message):
    # check for commands
    # remove command without running callback
```

`myplugin.py`
```
def do_deploy_master():
    subprocess.call(["git", "push", "heroku", "master"])

@respond_to("^deploy master$")
def ask_deploy_master(self, message):
    jobutils.save_command("deploy", self.do_deploy_master, message)
```

Excuse my extreme psuedocode, but this is sort of what I'm thinking. You can use the `save_command` function in any function that you want to confirm.

**Comment by skoczen** [comment]
@chutes great idea, and @brandonsturgeon love the direction. 
I'll ping and reply more on this later (about to run), but I've got another pattern I've been poking around with around giving methods access to context in a more general way, and/or support for creating multi-step processes. Either or both of those would be my ideal way to handle these kinds of features!

**Comment by chutes** [comment]
@skoczen thanks.  I'm happy to see that this project is still a little active.

**Comment by chutes** [comment]
@brandonsturgeon I'm running into a problem with getting the active instance during the method call.

Job Utils already exists and I don't want to instantiate a new object.
If I use inheritance on my plugin, when I respond yes, will responds twice each trying to run the command.  (There are 2 instances of the plugin). 

If I instantiate the job utils plugin in my plugin and call it, there are still 2 instances of the job utils plugin and the job utils plugin responds twice. One instance knows of the command though and the other does not.

How do you use job utils in your method here?
`@respond_to("^deploy master$")
def ask_deploy_master(self, message):
    jobutils.save_command("deploy", self.do_deploy_master, message)`

**Comment by chutes** [comment]
I resolved the problem in my last comment by making these job utils a mixin for my plugin.

**Comment by skoczen** [comment]
Closing, since it sounds like it's resolved!
