### ISSUE TITLE
middleware

### ISSUE THREAD

**Issue by chutes** [skoczen/will#252]
I'm looking at creating a piece of middleware to isolate my local development environment.

In other words.... I want to catch all messages coming into will and decide if I want to continue or not.

Is there something already in place to support this?

One solution I've come across is with decorators.

`
def local_development(dev_user_name, dev_room):
    def wrap(func):
        def wrapped_func(*args, **kwargs):
            message = args[1]
            sender = message.sender
            room = message.room

            if room and sender:
                if dev_room == room['name'] and dev_user_name == sender['name']:
                    return func(*args, **kwargs)

            return

        return wrapped_func

    return wrap
`

used by some plugin...

`@respond_to("^(?P<command>.*)$")
    @local_development(settings.DEV_USER, settings.DEV_ROOM)
    def parse_command(self, message, command):
        
        self.reply(message, 'I do work!')`

I don't like the necessity of decorating my method for local dev work and then removing the decorator before committing my work.

**Comment by chutes** [comment]
revised the above decorator to work even when DEV_USER and DEV_ROOM are not defined

`def local_development(func):
    def wrapped_func(*args, **kwargs):
        message = args[1]
        sender = message.sender
        room = message.room

        if hasattr(settings, "DEV_USER") and hasattr(settings, "DEV_ROOM"):
            if room and sender:
                if settings.DEV_ROOM == room['name'] and settings.DEV_USER == sender['name']:
                    return func(*args, **kwargs)

        else:
            return func(*args, **kwargs)

    return wrapped_func`

**Comment by skoczen** [comment]
So, for a lot of folks (including me), we develop using a local instance that's only targeted to one hipchat testing room, to facilitate plugin development.

Can you describe the broader need that's leading to this implementation?

**Comment by skoczen** [comment]
Closing this up since I haven't heard anything - please reopen if this is still a pain point!
