### ISSUE TITLE
Help messages aren't shown when using additional decorators

### ISSUE THREAD

**Issue by chutes** [skoczen/will#253]
I created custom decorators for my plugin methods that work below the respond_to decorator.

With my custom decorators in place, the help plugin no longer picks up my help messages

**Comment by skoczen** [comment]
I'd suspect this is with what your decorators are passing through, but without seeing them, it's impossible to say - can you share the code?

**Comment by skoczen** [comment]
Closing this up since I haven't heard anything - please reopen if you're still seeing this!
