### ISSUE TITLE
Formatting different Webhook replies

### ISSUE THREAD

**Issue by mbering** [skoczen/will#261]
I currently have two different plugins with webhooks set up. I would like one to reply using the '/code' command and the other to just reply regularly. However, unless they are both set up with '/code', it just replies with no formatting. I also would like one to reply with a green background and one with red, but have the same issue. 

Is this possible, am I doing something wrong?

class LogOutputPlugin(WillPlugin):

    @route("/log_output", method="POST")
    def log_output(self):
        """webhook: posts log output from tail plugin"""

        log_post_data = self.request.json
        log_msg = log_post_data['text']
        log_room_name = log_post_data['room']
        log_hip_rooms = self.available_rooms.keys()
        log_room = self.available_rooms.get(log_room_name)

        self.say("/code %(log_msg)s" % locals(), room=log_room, color="green")

class StatusAlertPlugin(WillPlugin):

    @route("/deploy_alert", method="POST")
    def deploy_alert(self):
        """webhook: alerts if tc did not deploy correctly after deploying from stash branch"""

        dep_post_data = self.request.json
        dep_msg = dep_post_data['text']
        dep_room_name = dep_post_data['room']
        dep_hip_rooms = self.available_rooms.keys()
        dep_room = self.available_rooms.get(dep_room_name)

        self.say("%(dep_msg)s" % locals(), room=dep_room, color ="red")

**Comment by skoczen** [comment]
@mbering very weird - it should definitely be possible - will see if I can reproduce locally!

**Comment by skoczen** [comment]
@mbering  suspect something else is happening here.  Here's what's working for me:

```python
from will.plugin import WillPlugin
from will.decorators import respond_to, periodic, hear, randomly, route, rendered_template


class LogOutputPlugin(WillPlugin):

    @route("/log_output", method="GET")
    def log_output(self):
        """webhook: posts log output from tail plugin"""

        log_post_data = self.request.json
        log_msg = "log message"
        self.say("/code %(log_msg)s" % locals(), color="green")

    @route("/deploy_alert", method="GET")
    def deploy_alert(self):
        """webhook: alerts if tc did not deploy correctly after deploying from stash branch"""

        dep_post_data = self.request.json
        dep_msg = "dep message"

        self.say("%(dep_msg)s" % locals(), color="red")
```

<img width="785" alt="screen shot 2017-05-24 at 6 36 41 pm" src="https://cloud.githubusercontent.com/assets/200635/26389857/0f62735a-40b0-11e7-92cc-77d6ae8a0eed.png">

**Comment by mbering** [comment]
Wow, sorry. After looking more closely I was sending the both sets of data to the same route. After changing that, it works as expected. 

Thanks.

**Comment by skoczen** [comment]
All good - feel free to bring troubles like this here!   It's a big community, and fixing stuff is fun. :)
