### ISSUE TITLE
Documentation is confusing Python modules with packages

### ISSUE THREAD

**Issue by DandyDev** [skoczen/will#267]
The documentation [here](http://skoczen.github.io/will/plugins/create/#whats-a-module) is defining a Python module as:

> Structurally, a will module is just a python module: a folder with an `__init__.py`.

That is incorrect. What the documentation is referring to, is called a _package_ in Python.

See here for clarification: https://www.learnpython.org/en/Modules_and_Packages

**Comment by skoczen** [comment]
PR is quite welcome. :)

**Comment by skoczen** [comment]
Closing this since the nomenclature will shift with #258 anyhow - if you'd like to put together a PR, feel free, I'll merge it!
