### ISSUE TITLE
Deploying WILL framework in docker container

### ISSUE THREAD

**Issue by lucifer1999** [skoczen/will#269]
Using WILL in personal linux system is quite different from deploying the same thing in docker i guess. Advice and guidance needed.

**Comment by skoczen** [comment]
Hey @lucifer1999 I'd love to see will ship with Docker support in the future, but as of now, we don't have anything set up.

As for getting him set up in a system though, docker is just linux, so it shouldn't be any different - install python, configure services for redis or whatever else you're using dependency-wise, `pip install`,  and you should be good to go!

**Comment by lucifer1999** [comment]
Error pops up while deploying in docker...

```
>  self.port = int(port)
> TypeError: int() argument must be a string or a number, not 'NoneType'
```

**Comment by lucifer1999** [comment]
I fixed above error but now i am facing problem with
 `_No connection adapters were found for '0.0.0.0:3013/keep-alive'`
This is public URL
Any advice here

**Comment by skoczen** [comment]
Make sure you're setting the port forwarding correctly on your container - I'd guess that it's not wired up somehow!

**Comment by lucifer1999** [comment]
Thanks I made it work..i was feeding ip address as 0.0.0.0 instead of http://0.0.0.0. Can you explain me why redis is used here. I know that it is used to store framework stuff. Any documentation will be helpful here or a brief summary will also do. Thanks again.

**Comment by skoczen** [comment]
Glad you got it working!

Redis - depending on what version you're using:
- Stable release: it's the default `STORAGE_BACKEND` - where will stores data.  They're pluggable, and you can choose different ones.
- Bleeding edge multi-platform Will:  Redis is both the default storage backend, and the default pubsub service (for intra-component messaging).  Both are pluggable, and multiple options exists.  That said, Redis Just Works, and works well, so I imagine it staying as the default for the forseeable future.
