### ISSUE TITLE
Limit on the size of string passed to the self.say() function 

### ISSUE THREAD

**Issue by syed-awais-ali** [skoczen/will#272]
Consider I am sending a list named `output` that formats to the `/code` syntax like this `self.say("/code {}".format("\n".join(output)))` to the hiphcat and that list contains a large amount of items, So is there a limit on the list or data that is big, because small lists are passed to the self.say() function and can be visible in hipchat room but when the list size increases it does not seem to pass it to the hipchat. I was just wondering if we can increase that limit because otherwise we have to divide a list into smaller chunks that it can accept. Is there any configuration option for `will` to increase that limit and amount of data that we can send through the self.say() function.

**Comment by skoczen** [comment]
At first glance, (and as far as I can remember) I can tell you that there isn't a limit on Will's side - but there is one on hipchat.

**Comment by syed-awais-ali** [comment]
Yeah, I checked the Hipchat API, the [message](https://developer.atlassian.com/hipchat/guide/sending-messages) parameter has a valid range of  1 - 10000. Thanks @skoczen
