### ISSUE TITLE
Will can't update available rooms for over 1000 rooms

### ISSUE THREAD

**Issue by jsfuchs** [skoczen/will#279]
There's a bug where will keeps requesting rooms starting at index 1000 over and over. I'll put in a PR ASAP, but this is breaking my will

**Comment by jsfuchs** [comment]
I see this was fixed, has it not yet been updated in pip?

**Comment by skoczen** [comment]
@jsfuchs Hm.  I *believe* this went out with 0.9.4, but I also don't have an org with > 1000 rooms to test it out.  Can you confirm what version you're on?

**Comment by skoczen** [comment]
The code for this fix is out - if someone is still seeing this issue, please re-open!
