### ISSUE TITLE
ERROR    No appropriate login method.

### ISSUE THREAD

**Issue by chutes** [skoczen/will#281]
occasionally when trying to start will, the error occurs.  After a number a retries, I can finally get it running...

output from ./run_will.py below...

      ___/-\___
  ___|_________|___
     |         |
     |--O---O--|
     |         |
     |         |
     |  \___/  |
     |_________|

      Will: Hi!

Verifying environment...
  ✓ WILL_USERNAME
  ✓ WILL_PASSWORD
  ✓ WILL_V2_TOKEN

Verifying credentials...
  ✓ Navi - Inventory Autmation authenticated
  ✓ @Navi verified as handle

Loading configuration...
  Importing config.py... 
    ✓ Valid.
  Verifying settings... 
    ! Warning: no DEFAULT_ROOM found in the environment or config.  Defaulting to 'Navi Development', the first one.
    ! Warning: no PUBLIC_URL found in the environment or config.  Defaulting to 'http://localhost:9000'.
    ✓ ALLOW_INSECURE_HIPCHAT_SERVER
    ✓ ADMINS
    ✓ BUILDCONFIG_IP
    ✓ DEV_ROOMS
    ✓ DEFAULT_ROOM
    ✓ DEV_USERS
    ✓ FILE_DIR
    ✓ HTTPSERVER_PORT
    ✓ HANDLE
    ✓ HIPCHAT_SERVER
    ✓ NAME
    ✓ PLUGINS
    ✓ PLUGIN_BLACKLIST
    ✓ PASSWORD
    ✓ PUBLIC_URL
    ✓ REQUESTS_OPTIONS
    ✓ ROOMS
    ✓ STORAGE_BACKEND
    ✓ TEMPLATE_DIRS_PICKLED
    ✓ USE_PROXY
    ✓ USERNAME
    ✓ V1_TOKEN
    ✓ V2_TOKEN
    ✓ abspath
    ✓ dirname
    ✓ os

Verifying rooms...
  ✓ Joining the 1 room specified.

Bootstrapping storage...
  ✓ Bootstrapped!

Bootstrapping plugins...
  
  Buildconfig ---------------------------------------------------------------------- plugins
    ✓ Build
  
  Buildconfig Commands: ------------------------------------------------------------ plugins
    ✓ ERT
    ✓ RoomInformation

Verifying settings requested by plugins...
  
Bootstrapping complete.

Starting core processes:
  ✓ Web server started.
  ✓ Scheduler started.
  ✓ Chat client started.
  ✓ Will is running.
ERROR    No appropriate login method.
ERROR    Error reading from XML stream.

**Comment by skoczen** [comment]
Hmm.  That *reads* like a credential/token problem, but the fact that it's intermittent suggests not.  Have any more info on this?

**Comment by skoczen** [comment]
Closing this up from a lack of reply - please reopen if you're still seeing this!
