### ISSUE TITLE
Plugin.say room parameter not user friendly

### ISSUE THREAD

**Issue by wontonst** [skoczen/will#289]
It didn't make sense to me how in configs we refer to rooms as strings but in `say` we need a `Room` object. The `Room` object isn't defined in the docs so the user would have to figure out how `Plugin` populates `self._available_rooms` to figure out everything works.

I propose we change the parameter to accept a room string, so going from

`self.say('the time is {} '.format(datetime.datetime.now()), room=self.available_rooms['CHEF'])`

to

`self.say('the time is {} '.format(datetime.datetime.now()), room='CHEF')`

If backwards compatibility is a big issue, we could do a typecheck to still support passing a Room object.

The code change would be simple and I'd be happy to submit a pull request.

**Comment by skoczen** [comment]
Hey @wontonst , thanks for the issue open and suggestion!

I love the idea of making it simpler and easier to use, and being able to pass either a room object (typically this is pulled off the message object), or a string is fantastic.   

A PR would be great - please note that a new release of Will (#258) is in the works with support for more than just hipchat, so if you need or create any methods not currently in `Room` or `RoomMixin`, please ping!

Thanks again for making Will better!

**Comment by wontonst** [comment]
Yeah looking at the code it's strange how `set_topic` and `schedule_say` already support string room names but `say` doesn't.

What's also strange to me is how `schedule_say` and `set_topic` allows you to set `ALL_ROOMS` but doesn't accept a list of rooms. For this reason I'm not going to let `say` take `ALL_ROOMS`. This might be a potential future improvement but I don't personally have a use for it.
