### ISSUE TITLE
NameError: name 'execfile' is not defined 

### ISSUE THREAD

**Issue by mike-love** [skoczen/will#296]
Seems like feature/shell-backend breaks py3 support a la markdownify-0.4.0

pip install git+https://github.com/skoczen/will.git@feature/shell-backend
Collecting git+https://github.com/skoczen/will.git@feature/shell-backend
  Cloning https://github.com/skoczen/will.git (to feature/shell-backend) to /tmp/pip-phvhx50m-build
Collecting hiredis==0.2.0 (from will==2.0.1b0)
  Downloading hiredis-0.2.0.tar.gz (46kB)
    100% |████████████████████████████████| 51kB 1.5MB/s 
Collecting redis==2.10.6 (from will==2.0.1b0)
  Downloading redis-2.10.6-py2.py3-none-any.whl (64kB)
    100% |████████████████████████████████| 71kB 2.9MB/s 
Collecting APScheduler==2.1.2 (from will==2.0.1b0)
  Downloading APScheduler-2.1.2-py2.py3-none-any.whl
Collecting beautifulsoup4==4.6.0 (from will==2.0.1b0)
  Downloading beautifulsoup4-4.6.0-py3-none-any.whl (86kB)
    100% |████████████████████████████████| 92kB 2.7MB/s 
Collecting bottle==0.12.7 (from will==2.0.1b0)
  Downloading bottle-0.12.7.tar.gz (69kB)
    100% |████████████████████████████████| 71kB 2.8MB/s 
Collecting CherryPy==3.6.0 (from will==2.0.1b0)
  Downloading CherryPy-3.6.0-py3-none-any.whl (453kB)
    100% |████████████████████████████████| 460kB 1.6MB/s 
Collecting clint==0.3.7 (from will==2.0.1b0)
  Downloading clint-0.3.7.tar.gz
Collecting dill==0.2.1 (from will==2.0.1b0)
  Downloading dill-0.2.1.tgz (45kB)
    100% |████████████████████████████████| 51kB 4.3MB/s 
Collecting dnspython==1.12.0 (from will==2.0.1b0)
  Downloading dnspython-1.12.0.zip (230kB)
    100% |████████████████████████████████| 235kB 1.7MB/s 
Collecting fuzzywuzzy==0.15.1 (from will==2.0.1b0)
  Downloading fuzzywuzzy-0.15.1-py2.py3-none-any.whl
Collecting Jinja2==2.7.3 (from will==2.0.1b0)
  Downloading Jinja2-2.7.3.tar.gz (378kB)
    100% |████████████████████████████████| 378kB 1.7MB/s 
Collecting Markdown==2.3.1 (from will==2.0.1b0)
  Downloading Markdown-2.3.1.tar.gz (267kB)
    100% |████████████████████████████████| 276kB 1.9MB/s 
Collecting MarkupSafe==0.23 (from will==2.0.1b0)
  Downloading MarkupSafe-0.23.tar.gz
Collecting natural==0.1.5 (from will==2.0.1b0)
  Downloading natural-0.1.5.tar.gz
Collecting parsedatetime==1.1.2 (from will==2.0.1b0)
  Downloading parsedatetime-1.1.2.tar.gz
Collecting python-Levenshtein==0.12.0 (from will==2.0.1b0)
  Downloading python-Levenshtein-0.12.0.tar.gz (48kB)
    100% |████████████████████████████████| 51kB 2.5MB/s 
Collecting pyasn1-modules==0.0.5 (from will==2.0.1b0)
  Downloading pyasn1-modules-0.0.5.tar.gz
Collecting pyasn1==0.1.7 (from will==2.0.1b0)
  Downloading pyasn1-0.1.7.tar.gz (68kB)
    100% |████████████████████████████████| 71kB 2.6MB/s 
Collecting pycrypto==2.6.1 (from will==2.0.1b0)
  Downloading pycrypto-2.6.1.tar.gz (446kB)
    100% |████████████████████████████████| 450kB 1.6MB/s 
Collecting pygerduty==0.28 (from will==2.0.1b0)
  Downloading pygerduty-0.28.tar.gz
Collecting pytz==2017.2 (from will==2.0.1b0)
  Downloading pytz-2017.2-py2.py3-none-any.whl (484kB)
    100% |████████████████████████████████| 491kB 1.5MB/s 
Collecting PyYAML==3.10 (from will==2.0.1b0)
  Downloading PyYAML-3.10.tar.gz (241kB)
    100% |████████████████████████████████| 245kB 1.8MB/s 
Collecting regex==2017.9.23 (from will==2.0.1b0)
  Downloading regex-2017.09.23.tar.gz (607kB)
    100% |████████████████████████████████| 614kB 1.4MB/s 
Collecting requests==2.18.4 (from will==2.0.1b0)
  Downloading requests-2.18.4-py2.py3-none-any.whl (88kB)
    100% |████████████████████████████████| 92kB 3.2MB/s 
Collecting six==1.10.0 (from will==2.0.1b0)
  Downloading six-1.10.0-py2.py3-none-any.whl
Collecting slackclient>=1.0.5<1.1.0 (from will==2.0.1b0)
  Downloading slackclient-1.0.9.tar.gz
Collecting markdownify>=0.4.0<0.5.0 (from will==2.0.1b0)
  Downloading markdownify-0.4.0.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-karjc9i0/markdownify/setup.py", line 12, in <module>
        execfile(os.path.join(os.path.dirname(__file__), 'markdownify', 'pkgmeta.py'),
    NameError: name 'execfile' is not defined
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-karjc9i0/markdownify/
/ # ^C
/ # ^C
/ # ^C
/ # ^C
/ # pip install markdownify
Collecting markdownify
  Using cached markdownify-0.4.0.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-cr95trde/markdownify/setup.py", line 12, in <module>
        execfile(os.path.join(os.path.dirname(__file__), 'markdownify', 'pkgmeta.py'),
    NameError: name 'execfile' is not defined
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-cr95trde/markdownify/

**Comment by skoczen** [comment]
[This commit](https://github.com/skoczen/will/commit/d1bf6db2341773091c9f93e6797ea4261bf3edaa) should fix this (does here.)

Fix is just to use a forked markdownify with python 3 support.  It's had an open PR waiting for merge for a year plus, so that's probably the shortest path to things working.

https://github.com/matthewwithanm/python-markdownify/pull/1

**Comment by skoczen** [comment]
Also, the latest on `feature/shell-backend` has full python3 support - there was a second external lib and the encryption functions weren't there yet.

**Comment by mike-love** [comment]
we're good here!  seems like that did the trick

**Comment by skoczen** [comment]
Fantastic!

**Comment by kamrankausar** [comment]
Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-urbb_ku6/mrjob/setup.py", line 18, in <module>
        execfile(join(dirname(__file__), 'mrjob/__init__.py'))
    NameError: name 'execfile' is not defined

**Comment by rsalmond** [comment]
Hey @kamrankausar, would you mind creating a new issue and including the specific branch / version of Will as well as the python version? Thanks!
