### ISSUE TITLE
'bool' object has no attribute 'lower'

### ISSUE THREAD

**Issue by rakeshdatta** [skoczen/will#298]
Hi All,

When I disabled 'ALLOW_INSECURE_HIPCHAT_SERVER', I get the error: 'bool' object has no attribute 'lower'

I want the communication between will plugin and my hipchat server through SSL. Can anyone plz guide me.

**Comment by skoczen** [comment]
Hey @rakeshdatta what version of Will as you using, and can you paste more of your config, and more of the error message?

You shouldn't need to set `ALLOW_INSECURE_HIPCHAT_SERVER` - it's disabled by default.

**Comment by skoczen** [comment]
Also, welcome! :)

**Comment by skoczen** [comment]
Also, taking my best guess at what's wrong without the above, it's possible you did:

`ALLOW_INSECURE_HIPCHAT_SERVER = "False"`

instead of 

`ALLOW_INSECURE_HIPCHAT_SERVER = False`

Maybe?

**Comment by skoczen** [comment]
@rakeshdatta any update on this?

**Comment by skoczen** [comment]
@rakeshdatta closing this up, please re-open if you're still having trouble!
