### ISSUE TITLE
Container builds failing on master 

### ISSUE THREAD

**Issue by mike-love** [skoczen/will#300]
Container builds fail with:

! config.py.dist exists.  Overwrite it? [y/n] Traceback (most recent call last):
  File "/usr/local/bin/generate_will_project", line 11, in <module>
    load_entry_point('will==2.0.1b1', 'console_scripts', 'generate_will_project')()
  File "/usr/local/lib/python2.7/site-packages/will/scripts/generate_will_project.py", line 159, in main
    if not os.path.exists(config_path) or ask_user("! config.py.dist exists.  Overwrite it?"):
  File "/usr/local/lib/python2.7/site-packages/will/scripts/generate_will_project.py", line 36, in ask_user
    response = input("%s [y/n] " % question)
EOFError: EOF when reading a line

**Comment by mike-love** [comment]
Working on this meow

**Comment by skoczen** [comment]
Oh, that makes sense.  We need to have a non-interactive mode.

**Comment by skoczen** [comment]
Heading out the door right now, but I can put this in tonight/tomorrow.

**Comment by mike-love** [comment]
@skoczen imo i don't think it's worth it; i already have a fix, we just pipe yes to all of the prompts, there's no harm doing it on build and theoretically we want all dependencies installed.  We won't know what the run time backend integration will be for containers and it will be harder to support multiple version's of the containers for different backends. 

Unless you can think of a reason not to, I should have this fixed in a few

**Comment by skoczen** [comment]
@mike-love That's good by me!
