### ISSUE TITLE
Tight loop causing 100% cpu usage

### ISSUE THREAD

**Issue by mattcl** [skoczen/will#304]
The following part of `bootstrap` in `main.py` is causing 100% cpu usage
https://github.com/skoczen/will/blob/97bd73262b0689c89fbdb824b7519fd2cb7658ad/will/main.py#L184-L200

The loop is infinite and without a sleep, so it just pegs the cpu. I've managed to monkeypatch the class in my current project, but this should probably be fixed. I don't know the intent here, so I'm unsure what the appropriate fix would be (I just disabled this loop).

**Comment by skoczen** [comment]
@mattcl thanks for the report - there was some cleanup here, so it's possible something slipped through!  FWIW, I'm not seeing it here, but I'm also currently running on a pretty hefty desktop. 

A couple questions:
1. What version of Will are you using?
2. I assume you're using the shell backend?

Thanks!
-Steven

**Comment by mattcl** [comment]
The machine I'm running this on is also relatively beefy, and I have this running in a docker container (without resource constraints).
1. will version is 2.0.1b2
2. I'm not actually using the shell backend, I was just tracking down where the loop was. 

I did a quick test and the CPU usage does not spike if I do enable the shell backend, so that's a possible workaround. Perhaps something about always executing this loop regardless of whether or not the backend is enabled?

**Comment by skoczen** [comment]
Hunh. That's super weird - that loop should only run if the shell is on!   Thanks for the info - I'll dig into it, and get a fix out!

**Comment by skoczen** [comment]
@mattcl What backends are you using?

**Comment by mattcl** [comment]
Just the slack backend. I suspect it's these lines where the var is always True:
https://github.com/skoczen/will/blob/97bd73262b0689c89fbdb824b7519fd2cb7658ad/will/main.py#L184-L188

**Comment by skoczen** [comment]
Yeah, I get that, but `readline()` isn't super heavy, and I'm not seeing the issue here.  I can easily add in a sleep in that loop, but would feel a lot better that it was solved if I could reproduce it first!

**Comment by mattcl** [comment]
I should note this is python 3.4 (I also had to monkeypatch markdownify)

I'm wondering if running in docker without tty means the `readline()` just returns instantly. If so, the while loop would just spin.

In any case if `readline()` responds immediately it should peg, since the sleep in the outer loop is never reached.

**Comment by skoczen** [comment]
Got it, that's helpful.  Have been testing in Py 2.7 and 3.6.

I've got what should be a fix here, but still not reproducing the CPU peg to verify.  Would you be able to do and install off github in your container to test?

Also, if you can submit a separate issue on the markdownify patch, that'd be really helpful. Thanks!

**Comment by mattcl** [comment]
I should be able to hack something in to patch in the fix to the container. As far as the markdownify patch, it's basically this https://github.com/matthewwithanm/python-markdownify/pull/1 . I have will-markdownify 0.4.0 and it lacks that fix. So I just monkeypatched the offending function before importing the rest of my dependencies.

**Comment by skoczen** [comment]
So, `will-markdownify` is a release that is specifically _for_ that fix, and it's working great in 3.6, fresh install here.   What error are you seeing?

**Comment by mattcl** [comment]
I assumed it should, but downloading the tarball from here https://pypi.python.org/pypi/will-markdownify And looking at __init__.py indicates that it doesn't import `six` and still uses `unicode(...)`.

**Comment by skoczen** [comment]
When you've got a second, give this a shot:

`pip install -e git+https://github.com/skoczen/will.git@bugfix/cpu#egg=will`

**Comment by mattcl** [comment]
@skoczen can confirm that that patch fixes my issue. I still don't know what's up with sources for `will-markdownify` not containing the patch for the `unicode(...)` invocation.

**Comment by skoczen** [comment]
@mattcl fantastic, thanks!    Will push a new release out shortly, and working with the original author to just get a fixed markdownify out on pypi.  Not sure what happened there either - totally possible I was on the wrong branch when I pushed that release - it's been a crazy couple of weeks. 

Thanks for all your help in getting this sorted!

**Comment by mattcl** [comment]
Thanks for the fast response! I'll close this issue.

**Comment by skoczen** [comment]
@mattcl This was just released (along with a fix for the markdownify patch) as `2.0.1beta3` - let me know if you hit any snags!
