### ISSUE TITLE
is there a good way to have a say or reply start a new thread?

### ISSUE THREAD

**Issue by netjunki** [skoczen/will#307]
I mucked around with exposing an is_threaded property through the system but the approach felt clunky

**Comment by skoczen** [comment]
So Will will automatically stay in a thread if it's been started - but am I right in assuming your use-case is something like:

```
You: @will, can you send me some updates that don't need to be in group chat?
  |-  Will: Sure, here's the info in a thread.
```

Is that right?

In that case, maybe a "`start_thread=True` param into `say()` and `reply()`?

**Comment by netjunki** [comment]
Yeah i think a start_thread=True parameter would do the job. Any follow on interaction in the thread would remain in the thread based on my experiments with the latest in master.

**Comment by skoczen** [comment]
Fantastic - will dig into the API, and see what we can do!

**Comment by skoczen** [comment]
This is in on [2.0.1b4](https://github.com/skoczen/will/pull/309), which will go out later today.

**Comment by netjunki** [comment]
Was trying this out and it doesn't seem to work. The code is looking for `"original_incoming_event"` in the event.source_message, but that doesn't seem to exist in my use case.

**Comment by skoczen** [comment]
Hm, this is working in 1-1 and rooms for me - what context are you testing in?

**Comment by netjunki** [comment]
1-1 and public channels.

**Comment by skoczen** [comment]
`say` or `reply`?

**Comment by skoczen** [comment]
Also, are you explicitly passing back a `message`, or just letting Will handle it?

**Comment by netjunki** [comment]
passing `message` back explicitly. Applying this patch made it work locally btw

                 try:
                     # If we're starting a thread
                     if "start_thread" in event.kwargs and event.kwargs["start_thread"] and ("thread_ts" not in data or not data["thread_ts"]):
    -                    if hasattr(event.source_message, "original_incoming_event"):
    +                    if hasattr(event.source_message.data, "original_incoming_event"):
                             data.update({
    -                            "thread_ts": event.source_message.original_incoming_event["ts"]
    +                            "thread_ts": event.source_message.data.original_incoming_event["ts"]
                             })
 
                     else:

**Comment by skoczen** [comment]
Right, but that depends on whether it's coming back via `say` or `reply` - I'm guessing you're using `say`?

**Comment by netjunki** [comment]
Correct, I'm using say.

**Comment by skoczen** [comment]
Ok, that's why.  Hmm.

I'm not sure that `say` makes sense when starting a thread - there's nothing to attach the thread to.  But I also get that's it's not necessarily intuitive unless you're thinking deeply about the difference.

**Comment by netjunki** [comment]
I see what you're saying though. Logically it makes sense that a new thread would be created with a reply. Additionally we want to flag to the person talking to will that the thread has been created.

**Comment by skoczen** [comment]
Right - thread only really makes sense if Will's replying to something (though I've documented this wrong.)

I see two scenarios to solve this:

1. Will gives a warning if `start_thread` is passed to `say`, telling the person to use `reply`.
2. `say` automagically turns into `reply` if `start_thread` is passed.

I'm honestly a bit on the fence on this one, and will want to mull it over a bit.

I've kept `say` and `reply` as different things in an attempt to reduce magic, and allow more natural contextual decisions.   I like the idea of keeping them distinct if they're adding clarity, but I dislike making someone understand a tiny nuance to get something relatively simple like threads working.

Ahh, design decisions. :)

**Comment by skoczen** [comment]
Alright, my decision on this is to:
1.  Only document `start_thread` on `reply()`.
2. Actually handle if it's passed into `say()`, but log a warning explaining that the plugin should be changed to `reply()`.
3. Silently ignore `start_thread` if `say()` is called from a webhook, etc and there's no `message` object to pull the thread from.

This will go out as 2.0.1-beta4 shortly!

**Comment by skoczen** [comment]
Out as 2.0.1-beta4!
