### ISSUE TITLE
@mention formatting is stripping out URLs

### ISSUE THREAD

**Issue by netjunki** [skoczen/will#308]
I want to be able to pass back formatted URLs since bot accounts can do that but the @mention formatting is stripping that out

**Comment by skoczen** [comment]
@netjunki can you provide a specific test case on this, so I can repo and get fixed?  Thanks!!

**Comment by skoczen** [comment]
I'm a big +1 to your broader idea - it's exactly what I'm hoping Will does - you write your plugin once, he takes care of all the tweaks and logic to get the formatting/etc right. 

I've made a fix for this - it looks just like a bug to me, but in the bigger question, I think it might make sense to standardize on some format (markdown?) that Will supports for formatting messages, then do the necessary magic to make it work everywhere.

All else equal, I'd probably go Markdown - your thoughts?

**Comment by netjunki** [comment]
I think Markdown is a good common markup for this use case. Not sure about the best way to go about implementing the chat system specific rendering. Though [mistune](https://github.com/lepture/mistune) looks like it provides a [promising feature set in this area](https://github.com/lepture/mistune#renderer).

**Comment by skoczen** [comment]
Love that idea - have used mistune in a few other projects, and it felt solid.  Opening up a new issue for this, probably as a ~2.2 feature.

**Comment by skoczen** [comment]
This is out as 2.0.1-beta4 - thanks for your help with specs and getting it sorted!
