### ISSUE TITLE
Default behavior or HIPCHAT_ROOMS is not working

### ISSUE THREAD

**Issue by vissree** [skoczen/will#312]
If I don't set HIPCHAT_ROOMS variable in config.py, the default behavior should be to join all rooms according to the documentation. However, I'm getting this error when I start will.

> Wed, 22 Nov 2017 08:11:33 [CRITICAL] Error starting io adapter will.backends.io_adapters.hipchat:
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/will/backends/io_adapters/base.py", line 116, in _start
    self.bootstrap()
  File "/usr/lib/python2.7/site-packages/will/backends/io_adapters/hipchat.py", line 771, in bootstrap
    backend_name=self.internal_name,
  File "/usr/lib/python2.7/site-packages/will/backends/io_adapters/hipchat.py", line 271, in start_xmpp_client
    for r in settings.HIPCHAT_ROOMS:
TypeError: 'NoneType' object is not iterable

**Comment by skoczen** [comment]
This could be a 2.x upgrade issue - thanks for reporting it, @vissree ! 

I'll dig into this tomorrow, and see if I can get it sorted!

**Comment by vissree** [comment]
Thanks @skoczen! Yes, I upgraded from 1.x to 2.x. Please let me know if you need more info.

**Comment by skoczen** [comment]
@vissree found and fixed!  This is fixed up in 2.0.2, which has been pushed up to pypi.  You should be able to just `pip install -U will` and have it be fixed.  Please let me know if you still have any trouble, and thanks again for the bug report!

**Comment by vissree** [comment]
Thanks @skoczen this works now!

**Comment by skoczen** [comment]
@vissree fantastic - thanks for following up, and reporting this!
