### ISSUE TITLE
Unexpected keyword argument 'message' in backends/execution/base.py

### ISSUE THREAD

**Issue by ptomkiel-oktawave** [skoczen/will#314]
Another one found due to upgrading will to 2.0.2 with existing custom plugins:
```
Traceback (most recent call last):
  File ".../python3.6/site-packages/will-2.0.2-py3.6.egg/will/backends/execution/best_score.py", line 38, in handle_execution
    self.execute(message, m)
  File ".../python3.6/site-packages/will-2.0.2-py3.6.egg/will/backends/execution/base.py", line 68, in execute
    instantiated_module = cls(message=message)
TypeError: __init__() got an unexpected keyword argument 'message'
```

Disabling my own plugins make will to start, but what've changed?

**Comment by skoczen** [comment]
So this (and the other one) make me wonder if your plugins are inheriting properly from `WillPlugin`.

Can you paste the plugin code, or send it as a 1-1 in the [Will slack channel](https://join.slack.com/t/heywill/shared_invite/MjEzNDMwNjE5NjMzLTE1MDAzMjQ3MTItYmVhZjVmMDk4ZQ)?

**Comment by ptomkiel-oktawave** [comment]
Same as in #313
