### ISSUE TITLE
generate_will_project should accept --backend [slack] [rocket] [shell] [hipchat] flag

### ISSUE THREAD

**Issue by wontonst** [skoczen/will#321]
I'm migrating to will 2.0 and the issue I'm hitting is in my dockerfile it hangs up at generate_will_project since it expects a user input of y/n. I'd like it so I can do

```
generate_will_project --backend shell hipchat
```

My current workaround is ugly:

```
printf 'n\ny\nn\ny' | generate_will_project
```

**Comment by skoczen** [comment]
Quick reply - saw this come in, think it's a great idea, would be totally open to a PR. (Ideally, comma-separate multiple backends?)

Also, tagging #324 on everything for this month, just to give a heads up.  Thanks for your patience!

**Comment by wontonst** [comment]
@skoczen PR for this up at #345

**Comment by wontonst** [comment]
Done in #345
