### ISSUE TITLE
FYI for December 2017

### ISSUE THREAD

**Issue by skoczen** [skoczen/will#324]
Hey everyone,

Just a quick heads up that I'll be slow on replies for all of December 2017 - I'm getting married in the middle of the month, and have friends and family traveling from halfway across the world to attend.  So - my time and energy will be with them while they're here!

Do know that I'll be back on Will at the end of the year, and caught up on your issues, PRs, and ideas!

If there are critical, show-stopper issues, please ping me (repeatedly) in [Slack](https://heywill.slack.com/shared_invite/MTgzNDIzMTg2MjkyLTE0OTQ4MTAyNDItYmJhNDI4ZDA4MA), and I'll try to find cycles to get them fixed!

Thanks for your patience, understanding, and for being part of the awesome community that makes Will better and better. :) 

-Steven

**Comment by wontonst** [comment]
Congratulations!

**Comment by dkcwd** [comment]
Congrats @skoczen 👍 enjoy!

**Comment by skoczen** [comment]
Thanks everyone - closing this up, as I'm now back to a semi-normal life! :)
