### ISSUE TITLE
Error in will.plugins.fun.wordgame - no string.letters in python 3

### ISSUE THREAD

**Issue by ptomkiel-oktawave** [skoczen/will#337]
I'm not sure if Will should work on both Python versions, but in Python 3 wordgame.py:211 shoudl be changed to:
`letter = random.choice(string.ascii_letters).upper()`

**Comment by skoczen** [comment]
Hey @ptomkiel-oktawave thanks for this report - all of Will should definitely work on py2 and py3.  Looks like @netjunki put a fix in, and this will be resolved in the upcoming 2.1.1!

**Comment by skoczen** [comment]
This has been fixed, and released in 2.1.1!
