### ISSUE TITLE
Can a plugin leave a room?

### ISSUE THREAD

**Issue by dpoirier** [skoczen/will#34]
I'd like to write a plugin that can have Will leave a room, but it doesn't seem possible at present.

Current plugins seem to only do things using the HipChat API, not the XMPP client, and they don't seem to have access to the WillBot object, which they'd need to get to the XEP_0045 plugin and call leaveMUC.

I could modify plugin initialization to pass in the WillBot object, but I wonder if there's some reason plugins don't have access to it now.

**Comment by binyata** [comment]
If you are using hipchat, this could be a potential solution to getting rid of the bot:

https://www.hipchat.com/docs/apiv2/method/remove_member

**Comment by skoczen** [comment]
So, given the length of time this has been open, and the underlying difficulties in ad-hoc join/leaves with configuration and restart, I'm closing this up for the moment.

Please reopen if this is still something that's needed!
