### ISSUE TITLE
Can we use slack oauth 2.0 token with will?

### ISSUE THREAD

**Issue by sumeetb** [skoczen/will#392]
I am trying to configure will to connect to slack. I have installed APP in my workspace and it has generated oauth token. But when i am using that token with SLACK_API_TOKEN i am getting error. Is there a way to use this as token or i need to generate legacy token? 
Looks like legacy token is not safe enough and will be deprecated in future by slack.

**Comment by rsalmond** [comment]
@sumeetb I believe you want to generate a bot account token, not an app token. Check out [this doc](https://api.slack.com/docs/token-types) detailing the token types available.

**Comment by Ashex** [comment]
For the time being you have to use legacy tokens.

https://api.slack.com/apps?new_classic_app=1

**Comment by pastorhudson** [comment]
Not trying to re-open, but this is changing in the new release right? And do we have documentation on how to setup the new token? If not I'm happy to write some.

**Comment by Ashex** [comment]
Yes this will change in the new release. There isn't any backend specific documentation right now but if you want to put together a getting started for slack and put it under maybe `docs/backends` that would be great. I'm going to update the required settings notice to the following:

```
        {
            "name": "SLACK_API_TOKEN",
            "obtain_at": "1. Go to https://api.slack.com/apps?new_classic_app=1"
            " and Configure your app.\n"
            '2. Install app in your workspace.\n'
            "3. Set Bot User OAuth Token (beginning with xoxb) as SLACK_API_TOKEN.",
        }
```

**Comment by pastorhudson** [comment]
Fantastic! I’ll see what I can come up with.
