### ISSUE TITLE
Does anyone have PyPI privileges?

### ISSUE THREAD

**Issue by wontonst** [skoczen/will#402]
Is there anyone here other than @skoczen who has credentials to push to PyPI?

**Comment by rsalmond** [comment]
We should get set up on travis as well. Then we can add PyPi creds to the travis secrets and have it push new versions when we cut a tagged release.

**Comment by skoczen** [comment]
@wontonst not yet.  :) What's your PyPI username?

**Comment by Ashex** [comment]
I've been granted PyPi privileges. @wontonst I see you have access so I'll close this out.
