### ISSUE TITLE
Ability to handle formatted messages is slack

### ISSUE THREAD

**Issue by birdman4512** [skoczen/will#407]
It would be really good if Will could handle formatted messages in slack. 
Maybe an option to feed in an array
Details at https://api.slack.com/docs/message-formatting

**Comment by rsalmond** [comment]
Hey @birdman4512, Will should be able to use any of those formatting sequences in any `say()` or `reply()` calls. 

Eg. `self.reply('<#{}|{}>'.format(slack_channel_id, slack_channel_name))`

Was there something more involved you were thinking?

**Comment by birdman4512** [comment]
Thanks for the reply, I realize now that my original request didn't cover the specifics I was looking for. 
I am wanting to attach an attachment to a message. The details are here -> https://api.slack.com/docs/message-attachments

Can the above be used to post these types of messages? and if so, would you mind providing me with an example?
Thanks in advance.

**Comment by rsalmond** [comment]
Ahh I understand! Another contributor has been working on a feature to provide exactly what you're looking for. If you are interested in trying it out I am sure your feedback would be very helpful! Check out #386.

**Comment by pastorhudson** [comment]
Just need to get the tests cleaned up, and colors fixed and #386 is almost ready
