### ISSUE TITLE
Respond back when Will doesn't understand a direct message

### ISSUE THREAD

**Issue by kowsik** [skoczen/will#41]
Sometimes users of our bot mistype things and _will_ just goes silent. Would be nice to have it respond with some default "I don't what you are talking about" message, if it's a directed message that doesn't match any of the `@respond_to` regexes.

**Comment by skoczen** [comment]
Just noting that this is supported in a general way (both default responses, and pluggable logic/matching backends) in #258, the next major will release.  Closing this, and tracking there!
