### ISSUE TITLE
unable to upgrade "wsgiref"

### ISSUE THREAD

**Issue by Megha-Navsoft** [skoczen/will#414]
Hi,
 I have Python 3.7 installed on my machine. I tried to follow step 2 and upgrade wsgiref using pip. It didn't work. Any idea on how to solve the issue? I do not want to switch to Python 2.

**Comment by rsalmond** [comment]
@Megha-Navsoft when it didn't work, what happened? Did you get an error message you can share with us to help determine the cause?

**Comment by pastorhudson** [comment]
@Megha-Navsoft Just putting this here incase people search issues. I believe wsgriref is pinned to a version that works with CherryPy. So you'll need a virtual environment that is built from will's requirements or it won't work.
