### ISSUE TITLE
Support unsolicitied direct file uploads

### ISSUE THREAD

**Issue by Ashex** [skoczen/will#429]
To solve for #428 

When will responds to a message in a channel by calling `send_file` it is not sent to the user in DM and silently fails.

**Comment by Ashex** [comment]
Making a note for when I get to writing a patch. The fix I added to my codebase was to open a DM channel when the name matches the user id prefix. Exact changes updated with events api:

**open_direct_message**
```python
    def open_direct_message(self, user_id):
        """Opens a DM channel."""
        return self.client._web_client.api_call(  # pylint: disable=protected-access
            "conversations.open",
            users=[user_id]
        )['channel']['id']
```

**get_channel_from_name**
```python
            # We need to check if a user id was passed as a channel
            # and get the correct IM channel if it was.
            elif name.startswith('U') or name.startswith('W'):
                return self.open_direct_message(name)
```

**Comment by pastorhudson** [comment]
This is what we did before. I’m glad to see this still works but is it full proof? Is there another way to know if the channel is really a dm?

**Comment by Ashex** [comment]
When an event is received from Slack via a channel it will be tagged with `is_direct` or `is_mpim` set to True. For outgoing with files it's still a bit messy, I'm merging these changes with my codebase so I've been going through it all and what I've determined so far:

* `is_direct` must be set to True in the payload
* The user id needs to be passed as the channel to `send_file`

I have it working reliably now but I had to modify send_file to not call  `set_data_channel_and_thread` and also pass kwargs to the data dictionary like so:

```python
    def send_file(self, event):
        'Sometimes you need to upload an image or file'

        try:
            logging.info('EVENT: %s', str(event))
            data = {}
            if hasattr(event, "kwargs"):
                data.update(event.kwargs)

            data.update({
                'filename': event.filename,
                'filetype': event.filetype
            })

            if event.kwargs.get("is_direct") is False or None:
                data = self.set_data_channel_and_thread(event, data=data)
```

**Comment by Ashex** [comment]
As for reliability, I need to reach out to slack support to verify this is still the case but I believe user ids will consistently begin with U or W.

**Comment by pastorhudson** [comment]
This is good stuff. I have a whitelisted channel feature so some of my bot commands will dm the person who sends the command of the channel isn’t whitelisted.
