### ISSUE TITLE
Bundle up will's deploy capabilities as a module

### ISSUE THREAD

**Issue by skoczen** [skoczen/will#43]
GK uses will to manage, stage, and deploy a variety of codebases on heroku. We have a set of will plugins that largely abstract out all the heroku config, and let anyone at the company do stuff like:

`@will stage new-branch`, and get a running stack in minutes.

This issue is for us to decouple the bits that are tied to our config, and offer this as a module for will, generally.

**Comment by derek-adair** [comment]
I'd recommend amending this enhancement to be an interface with any of the number of configuration management/deployment platforms out there...

* [Atlas](https://atlas.hashicorp.com/) (probably in the form of a [terraform](http://terraform.io/) plugin)
* [Ansible](http://www.ansible.com/application-deployment)
* [Chef](https://www.chef.io/)
* Etc...

The reason being... I dont use heroku but I would love to be able to do this.  Using one (or more) of these could provide a really easy interaction point for quite a powerful plugin.

**Comment by skoczen** [comment]
Docker is the most likely win for this - it will work on heroku, AWS, and really, pretty much anywhere.

**Comment by derek-adair** [comment]
I have a docker container that is running will, but it currently relies on [docker-compose](https://docs.docker.com/compose/) which is not "production ready".  Ansible or any of these configuration management systems would interact with Docker containers (or VMs) that configure redis, a python container and maybe even [hipchat server](https://www.hipchat.com/server).

**Comment by skoczen** [comment]
Closing this up, as it'll probably be revisited as an app, and possibly not as a part of core will!
