### ISSUE TITLE
Pass on message automatically

### ISSUE THREAD

**Issue by skoczen** [skoczen/will#44]
Sure would be nice if we didn't have to pass message around, and it could be passed through via the decorators.  See if that's possible in a simple, reliable way.

**Comment by camilonova** [comment]
That would be really cool

**Comment by borgstrom** [comment]
We could look into doing something like Flask's Request Context: http://flask.pocoo.org/docs/0.10/reqcontext/

That way anything that needed the current message could just import `from will import message` and get access to the current message.

**Comment by skoczen** [comment]
Ooh, that's an interesting idea.  A bit hairy in will's contexts, but a pattern that could definitely work.

**Comment by skoczen** [comment]
Yep, this is happening in the new arch, closing this up as it's not adding info/value!
