### ISSUE TITLE
generate_will_project gives pkg_resources.VersionConflict

### ISSUE THREAD

**Issue by MattyDub** [skoczen/will#70]
I followed the instructions on the quickstart page (http://skoczen.github.io/will/). Pip appears to have installed Will and all prerequisites correctly. The final message was:

<pre>
Successfully installed will APScheduler Fabric Jinja2 Markdown MarkupSafe PyYAML argh args bottle clint dill dnspython ecdsa futures gevent ghp-import greenlet hiredis mkdocs natural paramiko parsedatetime pathtools pyandoc pyasn1 pyasn1-modules pycrypto pytz redis requests six sleekxmpp tzlocal watchdog
Cleaning up...
</pre>

When I ran generate_will_project, I got this:

<pre>
(will-bot)~/will-bot$ generate_will_project 
Traceback (most recent call last):
  File "/opt/.envs/will-bot/bin/generate_will_project", line 5, in <module>
    from pkg_resources import load_entry_point
  File "/opt/.envs/will-bot/local/lib/python2.7/site-packages/pkg_resources.py", line 2829, in <module>
    working_set = WorkingSet._build_master()
  File "/opt/.envs/will-bot/local/lib/python2.7/site-packages/pkg_resources.py", line 451, in _build_master
    return cls._build_from_requirements(__requires__)
  File "/opt/.envs/will-bot/local/lib/python2.7/site-packages/pkg_resources.py", line 464, in _build_from_requirements
    dists = ws.resolve(reqs, Environment())
  File "/opt/.envs/will-bot/local/lib/python2.7/site-packages/pkg_resources.py", line 643, in resolve
    raise VersionConflict(dist, req) # XXX put more info here
pkg_resources.VersionConflict: (Jinja2 2.7.3 (/opt/.envs/will-bot/lib/python2.7/site-packages), Requirement.parse('Jinja2==2.7.1'))
</pre>

Any ideas? If this helps, uname gives:

<pre>
Linux my-server 3.13.0-36-generic #63-Ubuntu SMP Wed Sep 3 21:30:07 UTC 2014 x86_64 x86_64 x86_64 GNU/Linux
</pre>

It's python 2.7.6.

**Comment by PrideRage** [comment]
I still get this error with Jinja2==2.7.3
But if I install Jinja2==2.7.1 then it says: "pkg_resources.DistributionNotFound: Jinja2==2.7.3"
What can I do?

**Comment by skoczen** [comment]
Hi @PrideRage - you should just be able to `pip uninstall jinja2`, then `pip install will --upgrade`. 

The newer releases specify 2.7.3, and it's working here!

If it's not working there after the uninstall and reinstall of will, can you paste the output logs for the second command?  Also, just to makes sure things are clean, are you running in a virtualenv?

Thanks!
-Steven

**Comment by PrideRage** [comment]
Hey.
I've tried to do that now, but it still doesn't work. Here's the output log for "pip install will --upgrade": http://pastebin.com/2CmSF9Jc

Also, yes I am running in a squeaky clean virtualenv.

**Comment by skoczen** [comment]
@PrideRage That paste looks like it worked fine.  What's the error you get?

**Comment by PrideRage** [comment]
Traceback (most recent call last):
  File "/home/admin/Envs/will/bin/generate_will_project", line 5, in <module>
    from pkg_resources import load_entry_point
  File "/home/admin/Envs/will/local/lib/python2.7/site-packages/pkg_resources.py", line 2720, in <module>
    parse_requirements(__requires__), Environment()
  File "/home/admin/Envs/will/local/lib/python2.7/site-packages/pkg_resources.py", line 592, in resolve
    raise VersionConflict(dist,req) # XXX put more info here
pkg_resources.VersionConflict: (Jinja2 2.7.3 (/home/admin/Envs/will/lib/python2.7/site-packages), Requirement.parse('Jinja2==2.7.1'))

**Comment by skoczen** [comment]
Thanks much @PrideRage  - that's helped track it down. mkdocs, the library we use to generate docs, requires 2.7.1.  Since it's not needed to run will, pushing out a version in a minute that removes it from requirements!  

Will post when it's out.

**Comment by PrideRage** [comment]
Thanks a lot mate, you're awesome!

**Comment by skoczen** [comment]
0.6.5 is out - you should just be able to `pip install will --upgrade`, and be good to go!

And absolutely - thanks for taking the time to report this and submit logs!  You've fixed the latest release for lots of people!

**Comment by PrideRage** [comment]
Honestly I should thank you for even seeing this. I thought that because this issue was closed, you would just ignore further comments.

**Comment by skoczen** [comment]
Nah, oddly enough, my will pings me anytime some posts on the project. :)

Plus, ignoring problems would sort of clash with [our culture](http://skoczen.github.io/will/improve/#our-culture)!
