### ISSUE TITLE
On User Connect

### ISSUE THREAD

**Issue by pnurkkala** [skoczen/will#73]
Is there a way for Will Bot to "listen" to when users connect?

**Comment by skoczen** [comment]
Hey @pnurkkala ,

I'm just tidying up issues - since it's been a while since I've heard on this one, I'm closing it up.  If you're still interested in the functionality, please re-open so we can talk architecture!

Thanks,
Steven

**Comment by pnurkkala** [comment]
Steven,

Go ahead and close it up -- I've got too many projects going on atm. :-(

Thanks for checking it! Still love the bot!

Paul

On Thu, Apr 23, 2015 at 3:40 PM, Steven Skoczen <notifications@github.com>
wrote:

> Hey @pnurkkala <https://github.com/pnurkkala> ,
>
> I'm just tidying up issues - since it's been a while since I've heard on
> this one, I'm closing it up. If you're still interested in the
> functionality, please re-open so we can talk architecture!
>
> Thanks,
> Steven
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/skoczen/will/issues/73#issuecomment-95695653>.
>



-- 
[image: logo]
*Paul Nurkkala* Lead Developer
Tel: *952.412.7621*
pnurkkala@sellsgroup.com

**Comment by skoczen** [comment]
Sounds great, thanks!
