### ISSUE TITLE
SyntaxError: invalid syntax with sorted_help in main.py

### ISSUE THREAD

**Issue by JPerkster** [skoczen/will#74]
If I remove lines 329 & 330, the bot fires up, but help errors out.  

(18:31:57)-> ./qabot.py
Traceback (most recent call last):
  File "./qabot.py", line 2, in <module>
    from will.main import WillBot
  File "/home/cpsaurus/will/will/main.py", line 329
    sorted_help = {k: sorted(v) for k,v in self.help_modules.items()}
                                  ^
SyntaxError: invalid syntax
(18:33:41)-> python -V
Python 2.6.6

**Comment by JPerkster** [comment]
Hi,

As a note, the quick start guide advises Python 2.6 is required.  It might be good to update it to advise 2.7 is required.

http://skoczen.github.io/will/

**Comment by skoczen** [comment]
That is a very fine point.  And honestly, this isn't that tough to fix, if it's just this one list comp.  Reopening!

**Comment by skoczen** [comment]
Just a note that this will be fixed and going out in the release today. Thanks for raising this issue, and sticking through it when I did a bit of a blow-off.  Much appreciated!

**Comment by skoczen** [comment]
Released in [0.7.2](http://skoczen.github.io/will/improve/)!
