### ISSUE TITLE
AttributeError: 'module' object has no attribute 'PLUGINS'

### ISSUE THREAD

**Issue by i128** [skoczen/will#80]
When attempting to run_will.py, the following error is generated:

Traceback (most recent call last):
  File "./run_will.py", line 5, in <module>
    bot = WillBot()
  File "/tmp/will/will/main.py", line 63, in **init**
    plugins = settings.PLUGINS
AttributeError: 'module' object has no attribute 'PLUGINS'
Exception KeyError: KeyError(27928528,) in <module 'threading' from '/usr/lib/python2.7/threading.pyc'> ignored

This is from the current pull from here.  And from what I can tell settings under ./will/settings.py, does not have a PLUGIN function. Thoughts?

**Comment by ash-at-github** [comment]
We are facing similar issue. Adding domain name in quotes resolved the issue of plugin. But we are getting connection issue now. "gaierror no nodename nor servname provided", fix to which seems to be(as per google searches) using servername without quotes :/ 
Any idea how to fix this?
