### ISSUE TITLE
Project missing tags for recent releases

### ISSUE THREAD

**Issue by crccheck** [skoczen/will#84]
I usually check the [releases](https://github.com/skoczen/will/releases) page to see what the current version of will is, but it's still stuck on 0.4.10. Bringing that up to date will make it easier for people to know what the current release is and see what changed between versions.

**Comment by skoczen** [comment]
Good catch - there was a script that did this on deploy that was disappeared when the company that will was originally developed at shut down overnight.  Will get this re-added, and the future releases in!

**Comment by skoczen** [comment]
There is now a deploy script that does this properly.  Closing this issue up!

**Comment by skoczen** [comment]
And thanks much for the report!  I've credited you in the [release](http://skoczen.github.io/will/improve/#releases), let me know if you'd like different attribution.

**Comment by crccheck** [comment]
thanks, it's all good
