### ISSUE TITLE
Will cannot connect to internal servers with invalid certificates

### ISSUE THREAD

**Issue by sivy** [skoczen/will#85]
Since Atlassian released the Hipchat Server beta (http://hipchat.com/server) we are testing Hipchat behind the firewall. The internal service has an internal wildcard certificate, and will (by way of the requests library) is not set up to handle insecure connections to settings.HIPCHAT_SERVER.

    (willdev)sivy@ubuntu:~/projects/willdev/will$ ./start_dev_will.py 

          ___/-\___
      ___|_________|___
         |         |
         |--O---O--|
         |         |
         |         |
         |  \___/  |
         |_________|
               
          Will: Hi!

    Verifying environment...
      ✓ WILL_USERNAME
      ✓ WILL_PASSWORD
      ✓ WILL_V2_TOKEN
      ✓ WILL_REDIS_URL

    Verifying credentials...
    Process Process-1:
    Traceback (most recent call last):
      File "/usr/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
        self.run()
      File "/usr/lib/python2.7/multiprocessing/process.py", line 114, in run
        self._target(*self._args, **self._kwargs)
      File "/home/sivy/projects/willdev/will/will/mixins/hipchat.py", line 88, in get_hipchat_user
        r = requests.get(url)
      File "/home/sivy/envs/willdev/local/lib/python2.7/site-packages/requests/api.py", line 59, in get
        return request('get', url, **kwargs)
      File "/home/sivy/envs/willdev/local/lib/python2.7/site-packages/requests/api.py", line 48, in request
        return session.request(method=method, url=url, **kwargs)
      File "/home/sivy/envs/willdev/local/lib/python2.7/site-packages/requests/sessions.py", line 451, in request
        resp = self.send(prep, **send_kwargs)
      File "/home/sivy/envs/willdev/local/lib/python2.7/site-packages/requests/sessions.py", line 557, in send
        r = adapter.send(request, **kwargs)
      File "/home/sivy/envs/willdev/local/lib/python2.7/site-packages/requests/adapters.py", line 420, in send
        raise SSLError(e, request=request)
    SSLError: [Errno 1] _ssl.c:510: error:14090086:SSL  routines:SSL3_GET_SERVER_CERTIFICATE:certificate verify failed

Proposed solution is to add support in `hipchat.py` and `rooms.py` for a new setting, `WILL_HIPCHAT_SERVER_VERIFY` that should be set to `NO` for internal, insecure services. This setting would be checked in the two files that use the hipchat API and the `verify=False` option added to the requests calls.

PR forthcoming.

**Comment by sivy** [comment]
Looks like this will also need a fix to the ssl cert handing in `listener.py`.

**Comment by wreiske** [comment]
+1. I ended up fixing this with a valid cert, but i'm still getting a "ERROR: We ran into trouble: 'Invalid OAuth session'"

**Comment by skoczen** [comment]
I'm torn on this and the accompanying #86 .  Surely the proper fix is to create a valid SSL cert, no?

**Comment by sivy** [comment]
Well yes the best thing is a valid certificate but for internal usage that's not always possible. It would be nice to have the option in will, perhaps with a launch message giving the warning?

--
Steve - steveivy@gmail.com

**Comment by skoczen** [comment]
Alright, I've come around to this - with the addition of a launch warning.

I'd also propose renaming `WILL_HIPCHAT_SERVER_VERIFY` to `WILL_ALLOW_INSECURE_HIPCHAT_SERVER`, to be more explicit.

If you can the launch warning (and the default value) to `settings.py` (See things like `V1_TOKEN`), we'll get this merged and out!

**Comment by skoczen** [comment]
And, somehow, I have a few spare hours this evening (mostly trying to distract myself from clicking refresh and generally going crazy as [polytester](https://github.com/skoczen/polytester) is blowing up on reddit.)  Releases are nerve-wracking!

Anyhow, all that rambling to say that I'm merging this in, making the changes I noted above, and should be putting it out in a release tonight!

**Comment by sivy** [comment]
Nice, the setting is better named and the warning appropriate. Thanks!

**Comment by skoczen** [comment]
This is out as [0.6.6](http://skoczen.github.io/will/improve/#releases) - thanks for your submission, patience, and most of all, for making will even better!
