### ISSUE TITLE
Will should allow plugins to keep their own templates directory

### ISSUE THREAD

**Issue by sivy** [skoczen/will#88]
It would be more pythonic for plugins to be able to be situated anywhere on the python path (I think they can be), but also keep their templates with them. I'd like to be able to maintain various plugins in their own projects, ie:

    plugin_project
    - setup.py
    - my_plugin
        - __init__.py
        - submodule
            - __init__.py
        - templates
            - my_plugin
                - feature.html

**Comment by skoczen** [comment]
That seems reasonable to me!

**Comment by PrideRage** [comment]
+1 for this. I don't use templates a lot in will but coming from Django I think that every plugin needs it's own template directory.

**Comment by sivy** [comment]
@skoczen if you have a suggestion for an architecture here I'm willing to take a stab at an implementation. I'd really like to be able to move our plugins to their own internal repos, and keep will largely pristine.

**Comment by skoczen** [comment]
Know I kept you waiting - [polytester](https://github.com/skoczen/polytester/) blew up on the reddits, and I've put all my spare cycles over there for the last day.  Thanks for your patience.

On this - Ironically, when I went to find the spot to have you dig in, I realized it's basically a two-line change. :)

So, it'll be going out shortly!

@PrideRage - I'm not 100% on board with every plugin *needing* a templates folder. The broader pattern for will is that you have your own codebase of it, and that tight coupling within that codebase is totally ok.

That said, I also come from years of django.  Thus, having the *option* to bundle templates and plugins seems like an obviously good design decision.

Look for the release shortly!

**Comment by skoczen** [comment]
This is out as [0.6.8](http://skoczen.github.io/will/improve/#releases).  Tested and working locally - please open an issue if you run into any snags!

**Comment by sivy** [comment]
Funny I found about the same two line change! I'll wait for your version while I test porting one of my plugins to its own package.

Personally I've never liked the "maintain your own fork" model or using code (the old octopress comes to mind too).

--
Steve - steveivy@gmail.com

**Comment by skoczen** [comment]
@sivy wait no more, it's out! :)

Yeah, there was a lot of noodling and soul-searching when that pattern was figured out (and I still have reservations about parts of it.)

In the end, the decision was that the gains (adding new, simple functionality to will takes <2 min, including deploy) outweighed the losses (tighter coupling, harder to share plugins, etc.)

Hubot takes a similar tack, though it's pure maintain-your-fork.

What I'd hoped to achieve with will was a sort of middle ground.  You'd have your own codebase that used will, get all the core will improvements just by pip upgrading, and you had (hopefully) the flex to use external, abstracted modules if you wanted to.  Your template suggestion actually makes that last bit a reality.

The rationale (if you're interested) behind keeping it simpler (no list of installable plugins, etc) was my frustration when trying to set up a bot with the current solutions.  They all hit me as over-architected monstrosities whose code had eclipsed their documentation.  There were install-and-configure plugins via chat capabilities, dynamic everything, and super strong abstractions.

But in the day to day of setting them up and using them, my team hated them.  Adding the stuff we wanted was a pain, even though the actual code we wanted to add was a simple, few-line script.

Thus was born will.  A bit more tightly coupled, with some convention over configuration, but super easy to add the functionality you wanted, fast.

Anyhow, somewhere, there should be a manifesto of sorts on all this stuff, but if you're interested, there it is!

Finally, thanks again for suggesting this, and making will even more flexible for varying philosophies!

**Comment by sivy** [comment]
Hi @skoczen,

Thanks for the quick turn-around, this is great!

I totally see the desire to keep things simple - I too have seen a lot of over-engineered code that seems to give too much friction to get up and going easily.

My thoughts on our internal plugins are evolving, I originally thought that we're set up a project-per-plugin system, but now I'm thinking it might be a package:

    - internal_chat_plugins
        - plugin.py
        - plugin2.py
        - plugin3.py
        + templates
            + etc

I don't know if this will work with this new approach, and I may stick with everything-in-will too! But having options is great, and overall I think you've kept a good balance between simplicity and flexibility.

**Comment by skoczen** [comment]
@sivy great to hear it!

So, looking quickly at your outline, I think that should absolutely work with the new system.  Just make sure that `internal_chat_plugins` is a python module, and the one you specify in `config.py`.  You'll be all set.  You could also group those plugins into submodules, and still have it be fine, but you'd need to split your templates into the submodules as well.

It might be worth a look at the [`MODULE_DESCRIPTION` stuff](http://skoczen.github.io/will/plugins/create/#what-about-that-awesome-help-text) that does the grouping for help text.  A lot of people have found it to be a useful principle for organizing things.

**Comment by sivy** [comment]
Cool! Testing now...

**Comment by sivy** [comment]
So if I understand correctly, using submodules would look like this:

    + internal_chat_plugins
        - __init__.py (with MODULE_DESCRIPTION)
        + plugin1
            + templates
                + plugin1
                    - template.html
            - __init__.py (with MODULE_DESCRIPTION)
        + plugin2
            + templates
                + plugin2
                    - template.html
            - __init__.py (with MODULE_DESCRIPTION)

Then any WillPlugin subclass in internal_chat_plugins.* would be loaded and could call `rendered_template('plugin1/teplate.html')`

**Comment by skoczen** [comment]
Yep, with one small change (no module_description on `internal_chat_plugins`, and one note:

```
+ internal_chat_plugins
    - __init__.py (No MODULE_DESCRIPTION)
    + plugin1
        + templates
            + plugin1
                - template.html
        - __init__.py (with MODULE_DESCRIPTION)
    + plugin2
        + templates
            + plugin2
                - template.html
        - __init__.py (with MODULE_DESCRIPTION)
```

The note: in your config.py, you'd include them like:

```python
PLUGINS = [
    # Built-ins
    # ...

    # Custom
    "internal_chat_plugins.plugin1",
    "internal_chat_plugins.plugin2",
]
```

It's looking for a templates directory directly in the listed plugin's root.

**Comment by sivy** [comment]
CAn the plugin loading do wildcards? `internal_plugins.*` ?

**Comment by skoczen** [comment]
Not for submodules*.  All plugins *within* a given module are loaded (so, in your original graph plugins1-3 would be loaded just by specifying `internal_plugins`), but submodules aren't recursed.

* Under the hood, what's technically happening is a pass-off to `imp.find_module`.  Of the top of my head, I don't know what it does if the last module is a *.  It *might* work. But I wouldn't promise stability of that feature going forward.

**Comment by skoczen** [comment]
Side note: calling it an evening here (Thailand time), will check in tomorrow if you've got outstanding questions!

**Comment by sivy** [comment]
That's fine and on rreflection it means you can have WIP plugins that are not loaded unless specified. 

:+1:

--
Steve - steveivy@gmail.com

**Comment by skoczen** [comment]
Great - and `PLUGIN_BLACKLIST` is also available to help in those WIP situations.
