### ISSUE TITLE
Errant line in main.py in 0.6.8?

### ISSUE THREAD

**Issue by dpoirier** [skoczen/will#94]
This line looks suspicious https://github.com/skoczen/will/blob/d46d4440c2e6023b38190565f4c7c08bf97cdb44/will/main.py#L97

Copy/paste error?

**Comment by skoczen** [comment]
Thank god for people like you.  Fixing and pushing 0.6.9 in a jiffy!

**Comment by skoczen** [comment]
Ah, that makes more sense - it doesn't actually change anything - that's why nothing broke in testing.  Phew.  Still pushing out shortly!

**Comment by skoczen** [comment]
[0.6.9](http://skoczen.github.io/will/improve/#releases) is out.  Thanks again for the quick catch, Dan.
