### ISSUE TITLE
Improve talkback regex

### ISSUE THREAD

**Issue by PrideRage** [skoczen/will#96]
Currently the talkback plugin only responds if a user types `that's what she said`.

Many people are lazy, however, so the majority will probably say `thats what she said`.

I propose this regex:
`that('s|s) what she said`
or alternatively:
`that(.s|s) what she said`

**Comment by skoczen** [comment]
+1 to option one by me.   Kids these days, leaving out apostrophes.  The nerve!

**Comment by PrideRage** [comment]
It's not just kids but also people who don't natively speak english.

**Comment by skoczen** [comment]
Oh, I know (I butcher Thai on a daily basis!) That was a joke that didn't make it through the bits :)

Trying to get a release of django-seo-js out tonight, but will see if I can squeeze this in after that.

**Comment by skoczen** [comment]
Released as [0.7.1](http://skoczen.github.io/will/improve/#releases)!  Thanks for the great suggestion!

**Comment by PrideRage** [comment]
Thanks for this. 
Argh again I "overengineered" the regex.

**Comment by skoczen** [comment]
For sure.

And heh, regexes are about the most [over-engineer-prone tech](http://xkcd.com/1171/) there is.  It's really style in this case.  I'd easily accept the case that your regexes are more readable.

**Comment by jessamynsmith** [comment]
I totally think this makes sense. The original bot allows you to configure phrases, and when I initially deployed it I had every variant of TWSS I could think of.
