### ISSUE TITLE
ERROR    No appropriate login method.

### ISSUE THREAD

**Issue by bestokes** [skoczen/will#97]
Hi, I'm getting an not-authorized when starting Will for the first time:

    DEBUG    Event triggered: ssl_cert
    DEBUG    SEND (IMMED): <stream:stream to='chat.hipchat.com' xmlns:stream='http://etherx.jabber.org/streams' xmlns='jabber:client' xml:lang='en' version='1.0'>
    DEBUG    RECV: <stream:stream version="1.0" from="chat.hipchat.com" id="4d8e20c80a294ce9">
    DEBUG    RECV: <stream:features xmlns="http://etherx.jabber.org/streams"><auth xmlns="http://jabber.org/features/iq-auth" /><auth xmlns="http://hipchat.com" /><mechanisms xmlns="urn:ietf:params:xml:ns:xmpp-sasl"><mechanism>PLAIN</mechanism></mechanisms></stream:features>
    DEBUG    SEND (IMMED): <auth xmlns="urn:ietf:params:xml:ns:xmpp-sasl" mechanism="PLAIN">SOMESTRING</auth>
    DEBUG    RECV: <failure xmlns="urn:ietf:params:xml:ns:xmpp-sasl"><not-authorized /></failure>
    INFO     Authentication failed: not-authorized
    DEBUG    Event triggered: failed_auth
    ERROR    No appropriate login method.

The string in SOMESTRING doesn't resemble my api key or anything I am responsible for. I wonder if this is the problem and my WILL_V2_TOKEN should be in place there. I suspect I've gone a bit wrong somewhere along the line. 

As far as I can tell my creds are all correct as will is able to authenticate and fully initialise before this happens. 

Any hints at all would be welcomed.

**Comment by skoczen** [comment]
Hey @bestokes - 

That's gotta be annoying! 
Generally, this would indicate one of your hipchat tokens is wrong.  I'd start debugging there.

Is there anything out of the ordinary (different server, etc) about your setup?

**Comment by bestokes** [comment]
Hi @skoczen - nothing really out of the ordinary here, its a centos 6 server, fully patched up with nothing else running on it. Does my hipchat admin need to do something on this account to enable it to be authorized?  My WILL_V2_TOKEN is correct, thats for oauth though right? Is there another place where I set an API token?

**Comment by skoczen** [comment]
@bestokes  You'll need a user for will, as well as V2 (and V1, if your org has >30 rooms) tokens.

See step 2 on [deploying your will](http://skoczen.github.io/will/deploy/#deploying-your-will) - do you have all of those set?

**Comment by bestokes** [comment]
Yep, check .. I have a special user, and I have these variables exported: WILL_V1_TOKEN, WILL_USERNAME, WILL_PASSWORD, WILL_V2_TOKEN. My org has hundreds of rooms, I guess this must be an issue with the V1 token ... I'll check in with my hipchat admin. Maybe I'm blocked from doing this somehow. 

Cheers for the quick response by the way.

**Comment by skoczen** [comment]
Hey, absolutely on the quick response - my will bot pings me anytime someone posts. :)

The last version also introduced an option to disable SSL, and I've noticed that your traceback addresses are http, not the default https.  Do you have that setting enabled, by chance?

It's also possible we have a bug there, let me know on that + what you hear back from your admin.  As long as will is a normal user, and your tokens are admin tokens, things should Just Work.

**Comment by bestokes** [comment]
No, that line was still commented. But even if I try setting ALLOW_INSECURE_HIPCHAT_SERVER = "True" I still get a not-authorized. I'll let you know when my admin has come back with a response. Cheers!

**Comment by skoczen** [comment]
Sounds good!

**Comment by skoczen** [comment]
Just a ping on this, to see if you got it solved!

**Comment by skoczen** [comment]
@bestokes ^

**Comment by bestokes** [comment]
Hi Steven, thanks for keeping track of it! I guess you can close this off for now. I had to drop this projet and pick up something more urgent, however it does seem to be an issue my end with API tokens. Cheers.

**Comment by skoczen** [comment]
Sounds good - if you do run into it again, please reopen!

Cheers!

**Comment by dinowais** [comment]
@skoczen i am getting same issue but only with new hipchat user. else its working fine with old users i tried with new admin user also. need help 😄 .

DEBUG    Event triggered: ssl_cert
DEBUG    SEND (IMMED): <stream:stream to='chat.hipchat.com' xmlns:stream='http://etherx.jabber.org/streams' xmlns='jabber:client' xml:lang='en' version='1.0'>
DEBUG    RECV: <stream:stream version="1.0" from="chat.hipchat.com" id="f54adbc18faff88a">
DEBUG    RECV: <stream:features xmlns="http://etherx.jabber.org/streams"><auth xmlns="http://jabber.org/features/iq-auth" /><auth xmlns="http://hipchat.com" /><mechanisms xmlns="urn:ietf:params:xml:ns:xmpp-sasl"><mechanism>PLAIN</mechanism><mechanism>X-HIPCHAT-OAUTH2</mechanism></mechanisms><authrestartlogic xmlns="http://hipchat.com" /><compression xmlns="http://jabber.org/features/compress"><method>zlib</method></compression></stream:features>
DEBUG    SEND (IMMED): <auth xmlns="urn:ietf:params:xml:ns:xmpp-sasl" mechanism="PLAIN">ADM4MTg0XzM4NjkwOTgARml0Ym90</auth>
DEBUG    RECV: <failure xmlns="urn:ietf:params:xml:ns:xmpp-sasl"><not-authorized /></failure>
INFO     Authentication failed: not-authorized
DEBUG    Event triggered: failed_auth
ERROR    No appropriate login method.
DEBUG    Event triggered: no_auth
DEBUG    Event triggered: failed_auth
DEBUG    Event triggered: session_end
DEBUG    SEND (IMMED): </stream:stream>
INFO     Waiting for </stream:stream> from server
DEBUG    Waiting for 3 threads to exit.
DEBUG    Stopped event runner thread. 2 threads remain.
DEBUG    Stopped send thread. 1 threads remain.
DEBUG    Quitting Scheduler thread
DEBUG    Stopped scheduler thread. 0 threads remain.
DEBUG    Event triggered: disconnected
DEBUG     ==== TRANSITION connected -> disconnected
